### ISSUE TITLE
node-pre-pyp install 

### ISSUE THREAD

**Issue by ryanbrown358** [mapbox/node-sqlite3#1000]
Having problems using npm to install sqlite3 as a dependency on my Linux machine 
Error code below 

sqlite3@4.0.0 install /home/ryan/Desktop/BackEndJavaScriptLessons/Persistence/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: Buffer.alloc is not a function
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/ryan/Desktop/BackEndJavaScriptLessons/Persistence/node_modules/sqlite3/node_modules/tar/lib/pack.js:32:20)
node-pre-gyp ERR! stack     at Module._compile (module.js:409:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
node-pre-gyp ERR! stack     at Module.load (module.js:343:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:300:12)
node-pre-gyp ERR! stack     at Module.require (module.js:353:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/ryan/Desktop/BackEndJavaScriptLessons/Persistence/node_modules/sqlite3/node_modules/tar/lib/create.js:6:14)
node-pre-gyp ERR! stack     at Module._compile (module.js:409:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
node-pre-gyp ERR! System Linux 4.15.0-22-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/ryan/Desktop/BackEndJavaScriptLessons/Persistence/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ryan/Desktop/BackEndJavaScriptLessons/Persistence/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 4.15.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "sqlite3" "--no-optional"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryan/Desktop/BackEndJavaScriptLessons/Persistence/npm-debug.log

**Comment by colinkeenan** [comment]
Same for me. Noticed it about a week ago. It does install on Linux after spending a lot of time building stuff first. While on Windows, it installs right away even though my Windows machine is much slower.

**Comment by ryanbrown358** [comment]
Ya i have Ubuntu, and its not working right, i checked g++ and the other to make sure they are updated and they are, i also uninstalled node and npm to bring them to the latest version but its still throwing the same errors as listed above

**Comment by oferze** [comment]
For what it's worth, this is my bottomo line after some extensive research and hair-pulling:

On Windows, you can't install the sqlite3 npm package on Node 10+
You have to use node 8.11.3 or whatever the minor version for 8.x is.

I did everything:
 - `npm i sqlite3 --build-from-source`
 - `npm install --unsafe-perm=true`
 - Windows build tools (`npm install --global --production windows-build-tools`)
 - Various hacks and extensive StackOverflow / googling

**Nothing worked.** Logs kept showing that sqlite cannot be built (and also that accessing binaries from Amazon S3 fails due to file access restrictions - e.g. 403 Forbidden).

So as of today, **the way to get sqlite3 to install on Windows is by uninstalling Node+NPM and doing a fresh install of 8.11.3 LTS** (https://nodejs.org/en/ should show you the most current LTS version).

In case you don't remember upgrading Node recently, it might have come with the latest Visual Studio update.

**Comment by ryanbrown358** [comment]
@oferze So if i try these steps on my Linux machine it might work? it works fine on my windows machine but linux is where im having some problems

**Comment by oferze** [comment]
@ryanbrown358 I'm not sure, didn't do it on my Ubuntu box yet but while researching it seemed to me that Linux would be even easier, a matter of updating g++ (as you did) but also gcc. Don't know.

**Comment by colinkeenan** [comment]
As I said before, it's building just fine (but takes much longer to build on Arch Linux than Windows). I have the following versions installed in Arch Linux:

nodejs 10.4.0
gcc 8.1.1 (which includes g++)

**Comment by ryanbrown358** [comment]
@oferze @colinkeenan i got it working! 

So i updated gcc, uninstall node and npm, downgraded node to 8.11 like @oferze had mentioned sqlite3 isnt working for 10+ and thats what i had, so went down to 8.11 :D should have done that in the first place lol, but its running now i can query my Database and all that fun stuff with sqlite3

**Comment by colinkeenan** [comment]
I think you had node 10.3 which wasn't working with sqlite3, but I have node 10.4 and it is working fine with sqlite3.
