### ISSUE TITLE
Sqlite3 version 3/4 not installing with Electron

### ISSUE THREAD

**Issue by PythonDevOp** [mapbox/node-sqlite3#1051]
I am trying to run SQLite on my Electron app but it is failing:

Node 8.10
OSX 10.13.3
NPM 6.4.1
Electron 3.0.3
Python 2.7

```
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 12, in <module>
    sys.path.insert(0, os.path.join(os.path.dirname(sys.argv[0]), 'pylib'))
AttributeError: 'module' object has no attribute 'path'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/user/Downloads/AngularElectron2-master/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/user/Downloads/AngularElectron2-master/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64" "--dist-url=https://atom.io/download/electron"
```

I tried doing `electron-rebuild` and have node gyp installed, but something is not working and I don't know how to interpret the error message. 

I have tried:

1. removing and re-installing `node_modules` with yarn instead of npm
2. `--runtime=electron --target=1.7.6 --dist-url=https://atom.io/download/electron`
3. `--runtime=electron --target=3.0.3 --dist-url=https://atom.io/download/electron`
4. `npm install --build-from-source`
5. deleting `~./node-gyp`

The project works fine on Windows 7x64

**Comment by PythonDevOp** [comment]
Opening issue on node-gyp as it might be a node-gyp issue given the first line of the error
