### ISSUE TITLE
Cannot install with `npm install sqlite3` on windows10

### ISSUE THREAD

**Issue by kenvix** [mapbox/node-sqlite3#1055]
Nodejs v8.11.4
Microsoft Windows 10.0.17763.1
```
C:\Work Station\NodeProjects\BcyAnnouncer>npm install --save sqlite3

> sqlite3@4.0.2 install C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.2 and node@8.11.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 54.231.49.138:443
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\build\Release\\sqlite3.lib
  database.cc
  node_sqlite3.cc
  statement.cc
  win_delay_load_hook.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or directory (compiling source file ..\src\node_sqlit
e3.cc) [C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or directory (compiling source file ..\src\database.c
c) [C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or directory (compiling source file ..\src\statement.
cc) [C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Work Station\\NodeProjects\\BcyAnnouncer\\node_modules\\sqlite3\\lib\\binding\\node-v57-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Work Station\\NodeProjects\\BcyAnnouncer\\node_modules\\sqlite3\\lib\\binding\\node-v57-win32-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\lib\binding\node-v57-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Work Station\\NodeProjects\\BcyAnnouncer\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.11.4
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Work Station\NodeProjects\BcyAnnouncer\node_modules\sqlite3\lib\binding\node-v57-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Work Station\NodeProjects\BcyAnnouncer\package.json'
npm WARN BcyAnnouncer No description
npm WARN BcyAnnouncer No repository field.
npm WARN BcyAnnouncer No README data
npm WARN BcyAnnouncer No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kenvi\AppData\Roaming\npm-cache\_logs\2018-10-12T11_20_28_468Z-debug.log
```
[2018-10-12T11_20_28_468Z-debug.log](https://github.com/mapbox/node-sqlite3/files/2472860/2018-10-12T11_20_28_468Z-debug.log)

**Comment by kenvix** [comment]
Sorry for disturbing. I noticed that it is a network error.

**Comment by GeraldLow** [comment]
how you fix this bro

**Comment by kenvix** [comment]
@GeraldLow check your network connection

**Comment by AleGap** [comment]
cant fix it.. it always happen when i try to install a new modules.. npm start doesnt saying that i have to add sqlite3.
Then when i try to install it.. i receive that error.
