### ISSUE TITLE
Node.js 11 not supported

### ISSUE THREAD

**Issue by kibertoad** [mapbox/node-sqlite3#1063]
There are no prebuilt node-sqlite3 binaries for Node.js 11, and when Travis attempts to build them instead, this error is thrown:

```
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o] Error 1
make: Leaving directory `/home/travis/build/tgriesser/knex/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v11.0.0/bin/node" "/home/travis/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v67-linux-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/travis/build/tgriesser/knex/node_modules/sqlite3
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v11.0.0/bin/node /home/travis/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v67-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/tgriesser/knex/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.4.0-101-generic
node-pre-gyp ERR! command "/home/travis/.nvm/versions/node/v11.0.0/bin/node" "/home/travis/build/tgriesser/knex/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/tgriesser/knex/node_modules/sqlite3
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/versions/node/v11.0.0/bin/node /home/travis/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/travis/build/tgriesser/knex/node_modules/sqlite3/lib/binding/node-v67-linux-x64 --napi_version=3 --node_abi_napi=napi' (1)
```

**Comment by mserajnik** [comment]
Can confirm that the build also fails for me under macOS 10.14 / Node.js 11.0.

**Comment by deltaskelta** [comment]
Can anyone see what the problem is here? I can't quite make out what is going on

**Comment by cspencer0101** [comment]
Are there plans to convert this project to using N-API?  It seems that issues such as this would be avoided in the future by using N-API.

I'd love to start using Node 11, but my project requires sqlite3, so I'm stuck with Node 10.x until the install gets fixed up.

**Comment by kewde** [comment]
#1072

**Comment by panther7** [comment]
Hi,
we are need this ASAP, because we using latest [nwjs](https://nwjs.io/) with nodejs11.
Thank you very much ;-)

**Comment by kibertoad** [comment]
@panther7 Fix is ready - https://github.com/mapbox/node-sqlite3/pull/1072, I think the only reason why it wasn't merged yet is that Appveyor is lagging behind and doesn't support node 11 yet. You can either go bug them or convince maintainers to merge appveyor change separately :)

**Comment by panther7** [comment]
@kibertoad

**Comment by magneticchen** [comment]
macOS 10.14 / Node.js 11.0 failed confirmed.

**Comment by panther7** [comment]
+1

**Comment by BackPacker777** [comment]
+1

**Comment by kewde** [comment]
I'll merge it this weekend, hopefully appveyor supports it as we rely on them to create the builds used in production.

**Comment by fionaabbott** [comment]
I've been getting this same error on Node.js 10.13.0, what would you suggest?

**Comment by kewde** [comment]
NodeJS 11 support has been added and the prebuilt packages should be available in a couple of hours, depending on the CI.

You can track the latest commit here:
https://github.com/mapbox/node-sqlite3/commits/master
