### ISSUE TITLE
Build error on windows 10 x64 and node.js 11

### ISSUE THREAD

**Issue by llc1123** [mapbox/node-sqlite3#1070]
```
> sqlite3@4.0.3 install C:\Users\llc\AppData\Roaming\npm\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.3/node-v67-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.3 and node@11.0.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.3 and node@11.0.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not writ
e lines to file "Release\obj\action_before_build\action_b.1409F021.tlog\action_before_build.lastbuildstate". The proces
s cannot access the file 'C:\Users\llc\AppData\Roaming\npm\node_modules\sqlite3\build\deps\Release\obj\action_before_bu
ild\action_b.1409F021.tlog\action_before_build.lastbuildstate' because it is being used by another process. [C:\Users\l
lc\AppData\Roaming\npm\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
  unpack_sqlite_dep
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\llc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\llc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\llc\\AppData\\Roaming\\npm\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\llc\\AppData\\Roaming\\npm\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\llc\AppData\Roaming\npm\node_modules\sqlite3
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by kewde** [comment]
NodeJS 11 is not yet supported.

**Comment by fionaabbott** [comment]
How about 10.13.0?

**Comment by kewde** [comment]
Closing in favor of #1063
