### ISSUE TITLE
sqlite node :  cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nilipta** [mapbox/node-sqlite3#1079]
#  After installing sqlite3@4.0.4 -
we find the below messages in terminal :
```
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/sqliteTest/node_modules/sqlite3/lib/binding/node-v67-linux-arm/node_sqlite3.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/sqliteTest/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)

```

We have obtained this error in both **node js version 8 and 11**.

Note: The shared file is still in the directory. The architecture is debian 9 stretch on compulab board armhf.

Thank you for your help in advance.

**Comment by kewde** [comment]
Hi,

I don't think ARM support is here yet, feel free to attempt rebuilding from source.
https://github.com/mapbox/node-sqlite3/issues/418
