### ISSUE TITLE
4.0.4 doesnt' work on node 11 with Windows

### ISSUE THREAD

**Issue by 10mitri** [mapbox/node-sqlite3#1082]
Still doesn't work on node 11 / Windows

internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'C:\MC\PERSO\dev\projet\node.js\node_modules\sqlite3\lib\binding\node-v67-win32-ia32\node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\MC\PERSO\dev\projet\node.js\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

**Comment by baumy1** [comment]
Same problem on 10.13.0

**Comment by ManzDev** [comment]
Same problem on 11.5.0

**Comment by kewde** [comment]
Please post the contents of `node_modules\sqlite3\lib\binding\`.
Thanks.

**Comment by 10mitri** [comment]
A new try with 4.0.6 works fine.
Thanks a lot.
