### ISSUE TITLE
Electron 3.0.10 Prebuilt binaries for windows

### ISSUE THREAD

**Issue by MuizMahdi** [mapbox/node-sqlite3#1092]
I'm having an issue building it. I have never hated windows anymore, with the 4GB MSBuild tools, anyhow, i would appreciate if someone uploaded prebuilt binaries for electron 3.0.10, thanks.

**Comment by developeryashraj** [comment]
I am facing the same issue. Prebuilt binaries for `electron 3.0.x` is missing. It is exactly the "most likely problem" that is specified in the [Wiki](https://github.com/mapbox/node-sqlite3/wiki/Binaries) but still helping by providing below details and logs.

* OS :- Windows 10 - 64 bit (4GB RAM)
* Node :- v8.11.2
* node-gyp :- v3.6.2
* sqlite3 :- 4.0.4
* electron :- 3.0.11

Below is the complete log of `npm install`

```
> electron@3.0.11 postinstall C:\Projects\petpooja_node_latest\petpooja_app\node_modules\electron
> node install.js


> petpooja@19.0.7 postinstall C:\Projects\petpooja_node_latest\petpooja_app
> electron-builder install-app-deps

  • electron-builder version=20.38.3
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=ia32
Error: C:\Program Files (x86)\nodejs\node.exe exited with code 1
Output:

> sqlite3@4.0.4 install C:\Projects\petpooja_node_latest\petpooja_app\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "C:\Projects\petpooja_node_latest\petpooja_app\node_modules\sqlite3\lib\binding\electron-v3.0-win32-ia32\node_sqlite3.node" is installed via remote

> snappy@5.0.5 install C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy
> node-gyp rebuild


C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  snappy-sinksource.cc
  snappy-stubs-internal.cc
  snappy.cc
  win_delay_load_hook.cc
  snappy.vcxproj -> C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy\build\Release\\snappy.lib
  binding.cc
  win_delay_load_hook.cc
c:\projects\petpooja_node_latest\petpooja_app\node_modules\nan\nan_maybe_43_inl.h(88): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\binding.cc) [C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy\build\binding.vcxproj]
  C:\Users\petpooja\.electron-gyp\iojs-3.0.11\deps\v8\include\v8.h(3107): note: see declaration of 'v8::Object' (compiling source file ..\src\binding.cc)
C:\Projects\petpooja_node_latest\petpooja_app\node_modules\nan\nan.h(816): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\binding.cc) [C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy\build\binding.vcxproj]
  C:\Users\petpooja\.electron-gyp\iojs-3.0.11\src\node.h(99): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\binding.cc)
C:\Projects\petpooja_node_latest\petpooja_app\node_modules\nan\nan.h(830): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\binding.cc) [C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy\build\binding.vcxproj]
  C:\Users\petpooja\.electron-gyp\iojs-3.0.11\src\node.h(92): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\binding.cc)
C:\Projects\petpooja_node_latest\petpooja_app\node_modules\nan\nan.h(844): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\binding.cc) [C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy\build\binding.vcxproj]
  C:\Users\petpooja\.electron-gyp\iojs-3.0.11\src\node.h(85): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\binding.cc)
C:\Projects\petpooja_node_latest\petpooja_app\node_modules\nan\nan.h(1457): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\binding.cc) [C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy\build\binding.vcxproj]
  C:\Users\petpooja\.electron-gyp\iojs-3.0.11\src\node.h(99): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\binding.cc)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\petpooja_node_latest\petpooja_app\node_modules\snappy
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snappy@5.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@5.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\petpooja\AppData\Roaming\npm-cache\_logs\2018-12-14T10_24_59_434Z-debug.log

    at ChildProcess.childProcess.once.code (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at _rebuild (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\Projects\petpooja_node_latest\petpooja_app\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\Projects\petpooja_node_latest\petpooja_app\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at _installAppDeps (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
    at then (C:\Projects\petpooja_node_latest\petpooja_app\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! petpooja@19.0.7 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the petpooja@19.0.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\petpooja\AppData\Roaming\npm-cache\_logs\2018-12-14T10_24_59_544Z-debug.log
```

@MuizMahdi Currently i am using latest version of electron 2.x ([2.0.15](https://github.com/electron/electron/releases/tag/v2.0.15)) to solve this prebuilt binary issue. Did you find any another way around to fix it?

**Comment by MuizMahdi** [comment]
@developeryashraj 

I have managed to easily rebuild it using Ubuntu, I'll probably use a VM to rebuild for windows if I couldn't find any other way.

My issue is in Microsoft visual studio build tools (I've tried every solution on the internet) when i try to rebuild. Did you try to build it from source? , maybe it`ll work out for you. 

Download windows-build-tools using `npm install --global windows-build-tools` and after it finishes downloading and installing, uninstall sqlite3 `npm uninstall -g sqlite3` then do `npm install sqlite3 --build-from-source --runtime=electron --target=3.0.11 --dist-url=https://atom.io/download/electron` to rebuild sqlite3 for electron 3.0.11, then check node_modules/sqlite3/lib/binding in your project folder, you'll find the built binaries there (electron-v3.0-linux-x64 in my case since I used Linux to rebuild), if it worked out, then I'll appreciate if you could upload the folder inside lib for me, since i would need to package my app for windows.
