### ISSUE TITLE
Travis fails mocha-tests on node.js 12.x missing GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by bkimminich** [mapbox/node-sqlite3#1173]
The following only happens on Node.js 12.x and could not be reproduced on my local Windows 10 machine. See build result on Travis-CI for comparison with passing other node.js versions (8, 10 and 11): https://travis-ci.org/bkimminich/juice-shop/builds/540410741

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/build/bkimminich/juice-shop/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.replacementCompile (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at ConnectionManager._loadDialectModule (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:74:14)
    at new ConnectionManager (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/sequelize.js:320:20)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/models/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.replacementCompile (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/routes/verify.js:1:35391)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.replacementCompile (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Suite.<anonymous> (/home/travis/build/bkimminich/juice-shop/test/server/verifySpec.js:11:18)
    at Object.create (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/test/server/verifySpec.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.replacementCompile (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/mocha.js:327:14)
    at Mocha.run (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/mocha.js:804:10)
    at Object.exports.singleRun (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/lib/cli/cli.js:63:6)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.replacementCompile (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at runMain (/home/travis/.node-spawn-wrap-7007-e561017234f7/node:68:10)
    at Function.<anonymous> (/home/travis/.node-spawn-wrap-7007-e561017234f7/node:171:5)
    at Object.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/nyc/bin/wrap.js:27:4)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at /home/travis/.node-spawn-wrap-7007-e561017234f7/node:178:8
    at Object.<anonymous> (/home/travis/.node-spawn-wrap-7007-e561017234f7/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by bkimminich** [comment]
Duplicate of https://github.com/mapbox/node-sqlite3/issues/1164
