### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SerenModz21** [mapbox/node-sqlite3#1190]
when i try to use it on my vps, i get this error 
```
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/home/user/BubbleBOT/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/user/BubbleBOT/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
user@VPS:~/BubbleBOT$
```

**Comment by kewde** [comment]
You need to run `npm install sqlite3` every time you change Node versions.

**Comment by SerenModz21** [comment]
i tried that but it didn't install/update anything
