### ISSUE TITLE
Build error with electron 6.0.0 & 6.0.4

### ISSUE THREAD

**Issue by niravbhimani53** [mapbox/node-sqlite3#1208]
Hi,

I am trying to install sqlite3 for my electron project and later rebuilding using the command for electron `npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=6.0.0 --dist-url=https://atom.io/download/electron`.

I have tried for electron 6.0.0 & 6.0.4.
My macOS version: 10.14.6.
Node: v10.16.0

I am getting this error ...
```
> sqlite3@4.1.0 install /Users/haru53/projects/webnovel-scraper/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
  CXX(target) Release/obj.target/node_sqlite3/src/backup.o
../src/backup.cc:78:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(backup->handle(), cb, 1, argv);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:82:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        EMIT_EVENT(backup->handle(), 2, argv);
        ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:105:17: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
                TRY_CATCH_CALL(handle(), cb, 1, argv);
                ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:119:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            EMIT_EVENT(handle(), 2, info);
            ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:167:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(info.This(), Nan::New("filename").ToLocalChecked(), filename, ReadOnly);
         ^
../../nan/nan_maybe_43_inl.h:117:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:168:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(info.This(), Nan::New("sourceName").ToLocalChecked(), sourceName, ReadOnly);
         ^
../../nan/nan_maybe_43_inl.h:117:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:169:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(info.This(), Nan::New("destName").ToLocalChecked(), destName, ReadOnly);
         ^
../../nan/nan_maybe_43_inl.h:117:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:170:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(info.This(), Nan::New("filenameIsDest").ToLocalChecked(), filenameIsDest, ReadOnly);
         ^
../../nan/nan_maybe_43_inl.h:117:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:188:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/backup.cc:236:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            TRY_CATCH_CALL(backup->handle(), cb, 1, argv);
            ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:255:5: warning: unused variable 'status' [-Wunused-variable]
    BACKUP_BEGIN(Step);
    ^
../src/macros.h:154:9: note: expanded from macro 'BACKUP_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/backup.cc:301:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            TRY_CATCH_CALL(backup->handle(), cb, 2, argv);
            ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/backup.cc:319:5: warning: unused variable 'status' [-Wunused-variable]
    BACKUP_BEGIN(Finish);
    ^
../src/macros.h:154:9: note: expanded from macro 'BACKUP_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/backup.cc:336:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(backup->handle(), cb, 0, NULL);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
14 warnings generated.
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:49:17: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
                TRY_CATCH_CALL(this->handle(), cb, 1, argv);
                ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:63:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            EMIT_EVENT(handle(), 2, info);
            ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:92:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            TRY_CATCH_CALL(handle(), cb, 1, argv);
            ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:96:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            EMIT_EVENT(handle(), 2, argv);
            ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:133:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(info.This(), Nan::New("filename").ToLocalChecked(), info[0].As<String>(), ReadOnly);
         ^
../../nan/nan_maybe_43_inl.h:117:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:134:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(info.This(), Nan::New("mode").ToLocalChecked(), Nan::New(mode), ReadOnly);
         ^
../../nan/nan_maybe_43_inl.h:117:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:144:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:190:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(db->handle(), cb, 1, argv);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:194:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        EMIT_EVENT(db->handle(), 2, info);
        ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:199:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        EMIT_EVENT(db->handle(), 1, info);
        ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:273:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(db->handle(), cb, 1, argv);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:277:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        EMIT_EVENT(db->handle(), 2, info);
        ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:282:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        EMIT_EVENT(db->handle(), 1, info);
        ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:297:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(info.This(), callback, 0, NULL);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:314:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(info.This(), callback, 0, NULL);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:421:5: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    EMIT_EVENT(db->handle(), 2, argv);
    ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:462:5: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    EMIT_EVENT(db->handle(), 3, argv);
    ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:507:5: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    EMIT_EVENT(db->handle(), 4, argv);
    ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:528:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:564:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            TRY_CATCH_CALL(db->handle(), cb, 1, argv);
            ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:568:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            EMIT_EVENT(db->handle(), 2, info);
            ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:573:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(db->handle(), cb, 1, argv);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:603:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(baton->db->handle(), cb, 1, argv);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:628:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:636:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
    sqlite3_enable_load_extension(baton->db->_handle, 1);
    ^
../src/database.cc:639:21: error: use of undeclared identifier 'sqlite3_load_extension'
    baton->status = sqlite3_load_extension(
                    ^
../src/database.cc:646:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
    sqlite3_enable_load_extension(baton->db->_handle, 0);
    ^
../src/database.cc:666:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            TRY_CATCH_CALL(db->handle(), cb, 1, argv);
            ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:670:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            EMIT_EVENT(db->handle(), 2, info);
            ^
../src/macros.h:105:5: note: expanded from macro 'EMIT_EVENT'
    TRY_CATCH_CALL((obj),                                                      \
    ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/database.cc:675:9: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
        TRY_CATCH_CALL(db->handle(), cb, 1, argv);
        ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
28 warnings and 3 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/haru53/projects/webnovel-scraper/node_modules/sqlite3/lib/binding/electron-v6.0-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/haru53/projects/webnovel-scraper/node_modules/sqlite3/lib/binding/electron-v6.0-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v6.0"
gyp ERR! cwd /Users/haru53/projects/webnovel-scraper/node_modules/sqlite3
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/haru53/projects/webnovel-scraper/node_modules/sqlite3/lib/binding/electron-v6.0-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/haru53/projects/webnovel-scraper/node_modules/sqlite3/lib/binding/electron-v6.0-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/haru53/projects/webnovel-scraper/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/haru53/projects/webnovel-scraper/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/haru53/projects/webnovel-scraper/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/haru53/projects/webnovel-scraper/node_modules/sqlite3/lib/binding/electron-v6.0-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/haru53/projects/webnovel-scraper/node_modules/sqlite3/lib/binding/electron-v6.0-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.0' (1)
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by kewde** [comment]
Hi,

I see you're using SQLCipher.
```
../src/database.cc:636:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
    sqlite3_enable_load_extension(baton->db->_handle, 1);
    ^
../src/database.cc:639:21: error: use of undeclared identifier 'sqlite3_load_extension'
    baton->status = sqlite3_load_extension(
                    ^
../src/database.cc:646:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
    sqlite3_enable_load_extension(baton->db->_handle, 0);
```

I think you might have to recompile SQLCipher with extension support enabled in case it's linking with your local sqlcipher library. Also when compiling the sqlcipher library, you will need to add additional flags.

https://github.com/sqlcipher/sqlcipher/blob/master/README.md
