### ISSUE TITLE
Build problem on 32bit Debian 10

### ISSUE THREAD

**Issue by tssk** [mapbox/node-sqlite3#1210]
```
  i486-openwrt-linux-musl-g++ -shared -pthread -rdynamic -m32 -L/home/safarik/openwrt/staging_dir/target-i386_pentium4_musl/usr/lib -L/home/safarik/openwrt/staging_dir/target-i386_pentium4_musl/lib -L/home/safar
ik/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.3.0_musl/usr/lib -L/home/safarik/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.3.0_musl/lib -znow -zrelro  -Wl,-soname=node_sqlite3.node -o Release/obj.ta
rget/node_sqlite3.node -Wl,--start-group Release/obj.target/node_sqlite3/src/backup.o Release/obj.target/node_sqlite3/src/database.o Release/obj.target/node_sqlite3/src/node_sqlite3.o Release/obj.target/node_sql
ite3/src/statement.o Release/obj.target/deps/sqlite3.a -Wl,--end-group 
/home/safarik/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.3.0_musl/lib/gcc/i486-openwrt-linux-musl/7.3.0/../../../../i486-openwrt-linux-musl/bin/ld: Release/obj.target/node_sqlite3/src/backup.o: direct GOT relocation R_386_GOT32X against `uv_default_loop' without base register can not be used when making a shared object
/home/safarik/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.3.0_musl/lib/gcc/i486-openwrt-linux-musl/7.3.0/../../../../i486-openwrt-linux-musl/bin/ld: failed to set dynamic section sizes: Success
collect2: error: ld returned 1 exit status
make[4]: *** [node_sqlite3.target.mk:144: Release/obj.target/node_sqlite3.node] Error 1
make[4]: Leaving directory '/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/safarik/openwrt/staging_dir/hostpkg/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.0-5-686
gyp ERR! command "/home/safarik/openwrt/staging_dir/hostpkg/bin/node" "/home/safarik/openwrt/staging_dir/hostpkg/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/lib/binding/node-v57-linux-ia32/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/lib/binding/node-v57-linux-ia32" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/safarik/openwrt/staging_dir/hostpkg/bin/node /home/safarik/openwrt/staging_dir/hostpkg/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/lib/binding/node-v57-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/lib/binding/node-v57-linux-ia32 --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.19.0-5-686
node-pre-gyp ERR! command "/home/safarik/openwrt/staging_dir/hostpkg/bin/node" "/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/safarik/openwrt/staging_dir/hostpkg/bin/node /home/safarik/openwrt/staging_dir/hostpkg/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/lib/binding/node-v57-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/safarik/openwrt/build_dir/target-i386_pentium4_musl/node-mozilla-iot-gateway-0.9.2/ipkg-install/usr/lib/node_modules/webthings-gateway/node_modules/sqlite3/lib/binding/node-v57-linux-ia32 --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/safarik/openwrt/tmp/npm-cache/_logs/2019-08-28T10_48_01_793Z-debug.log
```

From what I was able to find online the problem is probably that gcc is built with **--enable-default-pie**.

**Comment by tssk** [comment]
It works ok when installing from commandline directly using node v8.16.1 and npm v6.4.1. SO it must be something in the OpenWrt build environment.
