### ISSUE TITLE
sqlite3 bug.

### ISSUE THREAD

**Issue by BlueBird171** [mapbox/node-sqlite3#1227]
code:
const sql = require("sqlite3");
const db = new sql.Database("bot.sqlite");
console.log("Initialized database connection.")

const tables = {
	warnings: [
		"id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL",
		"snowflake TEXT NOT NULL",
		"reason TEXT NOT NULL",
		"warner TEXT NOT NULL",
		"guild TEXT NOT NULL",
		"time INTEGER NOT NULL"
	],
	bans: [
		"id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL",
		"snowflake TEXT NOT NULL",
		"guild TEXT NOT NULL",
		"unbannedAt INTEGER NOT NULL"
	],
	mutes: [
		"id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL",
		"snowflake TEXT NOT NULL",
		"guild TEXT NOT NULL",
		"unmutedAt INTEGER NOT NULL"	
	]
}

for(let table in tables) {
	sql.run(`CREATE TABLE ${table} (${tables[table].join(", ")})`, () => {
		console.log(`Initialized table "${table}".`);
	});
}

module.exports = db 

error:
const db = new sql.Database("bot.sqlite");
           ^
TypeError: sql.Database is not a constructor
    at Object.<anonymous> (/app/sql.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/events/message.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)

**Comment by BlueBird171** [comment]
please help ;-;
