### ISSUE TITLE
Multiple versions of node.js on windows 10 x64 Permission denied

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mapbox/node-sqlite3#1266]
```
f:\dev\project>npm install better-queue-sqlite
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> sqlite3@4.1.1 install f:\dev\project\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "f:\dev\project\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" is installed via remote

> sqlite3@4.0.1 install f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.1/node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.1 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.1 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  sqlite3.c
  sqlite3.c
f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3\build\Release\obj\global_intermediate\sqlite-autoconf-3240000\sqlite3.c : fatal error C1083: Cannot open compiler generated file: 'f:\dev\project\node_modules
\better-queue-sqlite\node_modules\sqlite3\build\deps\Release\obj\sqlite3\sqlite3.obj': Permission denied [f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3\build\deps\sqlite3.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v12.14.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\Dev\\FurnitureTree\\Mage2Importer\\node_modules\
\better-queue-sqlite\\node_modules\\sqlite3\\lib\\binding\\node-v72-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=F:\\Dev\\FurnitureTree\\Mage2Importer\\node_modules\\better-queue-sqlite\\node_modules\\sqlite3\\lib\\binding\\node-v72-win32-
x64" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=f:\dev\project\node_mod
ules\better-queue-sqlite\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3\lib\binding\node-v72-win32-x64 --napi_versi
on=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (f:\dev\project\node_modules\better-queue-sqlite\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Dev\\FurnitureTree\\Mage2Importer\\node_modules\\better-queue-sqlite\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3
node-pre-gyp ERR! node -v v12.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=f:\dev\project\node_modules\better-queue-sqlite\node_m
odules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=f:\dev\project\node_modules\better-queue-sqlite\node_modules\sqlite3\lib\binding\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-12-19T23_35_06_471Z-debug.log
```

**Comment by kewde** [comment]
Update sqlite3 to the latest version which supports Node V12.
