### ISSUE TITLE
node sqlite3 build error

### ISSUE THREAD

**Issue by nukolas** [mapbox/node-sqlite3#1275]
I am getting errors when trying to install sqlite3 for node on Raspberry Pi 3 (DietPi).  I've read about similar issues here and have tried a variety of options to get it to work, including with/without sudo, updating gcc/g++ compilers as well as nodejs, and also using "-build-from-source".

My terminal error output is below - seems that the issue is with a Python module import.  I'm running Python v2.7.

```
root@DietPi:~/gekko# python --version
Python 2.7.16
```

Can find anything via google for fixing the Python import error.

```
root@DietPi:~/gekko# sudo npm install sqlite3 --build-from-source

> sqlite3@4.1.1 install /root/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 7, in <module>
    import ast
ImportError: No module named ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/gekko/node_modules/sqlite3/lib/binding/node-v79-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/gekko/node_modules/sqlite3/lib/binding/node-v79-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /root/gekko/node_modules/sqlite3
gyp ERR! node -v v13.7.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/gekko/node_modules/sqlite3/lib/binding/node-v79-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/gekko/node_modules/sqlite3/lib/binding/node-v79-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/gekko/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.75-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/root/gekko/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/gekko/node_modules/sqlite3
node-pre-gyp ERR! node -v v13.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/gekko/node_modules/sqlite3/lib/binding/node-v79-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/gekko/node_modules/sqlite3/lib/binding/node-v79-linux-arm --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-26T23_07_53_597Z-debug.log
```

**Comment by nukolas** [comment]
O, I've fixed it now (as per usual after a day of trial an error and straight after posting the issue here...

I installed the python-dev headers and sqlite installed correctly.

`sudo apt-get install python-dev`
