### ISSUE TITLE
I got an error when I rebuild sqlite3 for electron

### ISSUE THREAD

**Issue by printjs** [mapbox/node-sqlite3#1300]
My environment is windows.

I set HTTPS_PROXY=https://127.0.0.1:1080 in my terminal.
I can got content of https://www.google.com for `curl https://www.google.com`;
But I can't access the address `https://electron.org/headers/v8.0.0/node-v8.0.0-headers.tar.gz`.
***Do you have any mirror url replace the `https://electron.org/headers`?***
```
node-pre-gyp WARN Using request for node-pre-gyp https download
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.107.60:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\tools\\node_modules\\sqlite3\\lib\\binding\\electron-v8.0-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\tools\\node_modules\\sqlite3\\lib\\binding\\electron-v8.0-win32-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v8.0" "--dist-url=https://electronjs.org/headers"
gyp ERR! cwd E:\tools\node_modules\sqlite3
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Program Files\nodejs\node.exe D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\tools\node_modules\sqlite3\lib\binding\electron-v8.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\tools\node_modules\sqlite3\lib\binding\electron-v8.0-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v8.0 --dist-url=https://electronjs.org/headers' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\tools\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "E:\\tools\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\tools\node_modules\sqlite3
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'D:\Program Files\nodejs\node.exe D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\tools\node_modules\sqlite3\lib\binding\electron-v8.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\tools\node_modules\sqlite3\lib\binding\electron-v8.0-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v8.0 --dist-url=https://electronjs.org/headers' (1)
npm WARN tool_electron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\heave\AppData\Roaming\npm-cache\_logs\2020-03-13T08_28_48_115Z-debug.log
```

**Comment by printjs** [comment]
@kewde Can you help me? Thanks

**Comment by bedwardly-down** [comment]
@printjs it should be `electronjs.org` not `electron.org`

**Comment by printjs** [comment]
@bedwardly-down OK，Thanks

**Comment by bedwardly-down** [comment]
Any updates on this bug, @printjs?

**Comment by kewde** [comment]
f12d3b0511beffe28487204cd6611f21ebd7e02e

**Comment by bedwardly-down** [comment]
Awesome!!! I missed that PR.
