### ISSUE TITLE
SQLite3 v4.2.0 on Windows 10 falls back to build, which fails

### ISSUE THREAD

**Issue by robogeek** [mapbox/node-sqlite3#1322]
I am on Windows 10, with Node.js 13.13.0.  I am installing a package that uses SQLite3.  When trying to do the install I get this:

 ```
PS C:\Users\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users> npm install sqlite3

> sqlite3@4.2.0 install C:\Users\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@13.13.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@13.13.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  unpack_sqlite_dep
  sqlite3.c
  sqlite3.c
C:\Users\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\node_modules\sqlite3\build\Release\obj\g
lobal_intermediate\sqlite-autoconf-3310100\sqlite3.c : fatal error C1083: Cannot open compiler generated file: 'C:\User
s\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\node_modules\sqlite3\build\deps\Release\obj\sql
ite3\sqlite3.obj': Permission denied [C:\Users\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\no
de_modules\sqlite3\build\deps\sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19613
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\heavy\\Documents\\nodewebdev\\Node.js-14-Web-Development\\Chapter10\\users\\node_modules\\sqlite3\\lib\\binding\\node-v79-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\heavy\\Documents\\nodewebdev\\Node.js-14-Web-Development\\Chapter10\\users\\node_modules\\sqlite3\\lib\\binding\\node-v79-win32-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd C:\Users\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\node_modules\sqlite3
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by kewde** [comment]
> Cannot open compiler generated file: 'C:\User
s\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\node_modules\sqlite3\build\deps\Release\obj\sql
ite3\sqlite3.obj': Permission denied [C:\Users\heavy\Documents\nodewebdev\Node.js-14-Web-Development\Chapter10\users\no
de_modules\sqlite3\build\deps\sqlite3.vcxproj]

Strange.

**Comment by kewde** [comment]
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v79-win32-x64.tar.gz

The binary downloads fine for me, perhaps a network issue?

**Comment by kewde** [comment]
Assuming network failure, closing.
```
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@13.13.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@13.13.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
```

If the issue persists for v5.0.0, re-open the issue and change the title.
