### ISSUE TITLE
 An unhandled error occurred inside electron-rebuild

### ISSUE THREAD

**Issue by alksily** [mapbox/node-sqlite3#1344]
```$ ./node_modules/.bin/electron-rebuild
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.4.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aleksey/.electron-gyp/9.0.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/aleksey/.electron-gyp/9.0.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/aleksey/.electron-gyp/9.0.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
make: вход в каталог «/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/build»
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Ошибка 127
make: выход из каталога «/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/usr/bin/node" "/home/aleksey/PhpstormProjects/nucleo/node_modules/.bin/node-gyp" "rebuild" "--target=9.0.3" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/lib/binding/electron-v9.0-linux-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.2.0/{toolset}/" "--package_name=electron-v9.0-linux-x64.tar.gz"
gyp ERR! cwd /home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.4.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aleksey/.electron-gyp/9.0.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/aleksey/.electron-gyp/9.0.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/aleksey/.electron-gyp/9.0.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
make: вход в каталог «/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/build»
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Ошибка 127
make: выход из каталога «/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/aleksey/PhpstormProjects/nucleo/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/usr/bin/node" "/home/aleksey/PhpstormProjects/nucleo/node_modules/.bin/node-gyp" "rebuild" "--target=9.0.3" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3/lib/binding/electron-v9.0-linux-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.2.0/{toolset}/" "--package_name=electron-v9.0-linux-x64.tar.gz"
gyp ERR! cwd /home/aleksey/PhpstormProjects/nucleo/node_modules/sqlite3
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/aleksey/PhpstormProjects/nucleo/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/aleksey/PhpstormProjects/nucleo/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/aleksey/PhpstormProjects/nucleo/node_modules/rxjs/internal/Subscriber.js:143:22)
```

**Comment by alksily** [comment]
Seriously, I had to read the documentation

```npm install serialport --build-from-source --unsafe-perm --runtime=electron --target=9.0.3 --dist-url=https://electronjs.org/headers```
