### ISSUE TITLE
Error installing sqlite3 manual

### ISSUE THREAD

**Issue by PrzemekSkw** [mapbox/node-sqlite3#1425]
Hello, I'm new to node, npm so forgive me. I try to install openvpn-status on Debian 10 server and have error `Error: Please install sqlite3 package manually`. I open that [thread](https://github.com/AuspeXeu/openvpn-status/issues/496). 
```
~/openvpn-status$ node server.js 
/home/przemek/openvpn-status/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88
        throw new Error(`Please install ${moduleName} package manually`);
        ^
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/przemek/openvpn-status/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/home/przemek/openvpn-status/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/home/przemek/openvpn-status/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/przemek/openvpn-status/node_modules/sequelize/lib/sequelize.js:324:20)
    at Object.<anonymous> (/home/przemek/openvpn-status/database.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/przemek/openvpn-status/server.js:11:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```
I try also `apt-get install sqlite libsqlite3-dev`, 
```
~/openvpn-status$ sudo  npm install nw-gyp -g
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 96 packages, and audited 97 packages in 6s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
~/openvpn-status$ npm install sqlite3 --build-from-source

up to date, audited 1581 packages in 4s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
~/openvpn-status$ sudo npm install -g node-gyp
[sudo] password for przemek: 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 97 packages, and audited 98 packages in 4s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
~/openvpn-status$ npm fund
openvpn-status@4.2.32
└── https://github.com/sponsors/RubenVerborgh
    └── follow-redirects@1.13.1
```
Please help because I don't understand any of this.
Regards,
Przemek

**Comment by kewde** [comment]
Hi,

Have you attempted to `npm install sqlite3`?.

**Comment by PrzemekSkw** [comment]
> Hi,
> 
> Have you attempted to `npm install sqlite3`?.

Hi, yes I try that also.

**Comment by kewde** [comment]
Hi,

I'm closing the issue, I believe this in an issue in the "sequalize" module. Please open up an issue there.
You can still comment here and seek help but I do have to close it given that it's not an issue in our library.
