### ISSUE TITLE
Fails to instanciate node_sqlite3

### ISSUE THREAD

**Issue by simonech** [mapbox/node-sqlite3#254]
Hi,
I'm running latest code of Ghost on Windows Azure WebSites (in free mode, so only 32bit version is allowed) and application fails to run.
Before it was running perfectly fine.

Ghost is using node-sqlite 2.1.19

The error I get is:

```
[31m
ERROR:[39m [31mCannot find module './binding\Release\node-v11-win32-x64\node_sqlite3.node'[39m

Error: Cannot find module './binding\Release\node-v11-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sqlite3\lib\sqlite3.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17) 
```

While on installed on my folder is node_modules\sqlite3\lib\binding\Release\node-v11-win32-ia32\node_sqlite3.node

Not sure where the bug here is might be, either the selection done by the Binary.js or the install from npm, but looks like the version of npm is ok as the process is 32bit indeed

**Comment by J4G-** [comment]
I'm still getting this issue on Azure Websites using ghost.
