### ISSUE TITLE
Cannot build for x64, node-webkit 0.11.1, Mac OS X

### ISSUE THREAD

**Issue by timothyha** [mapbox/node-sqlite3#366]
Hello, I cannot build sqlite3 for node-webkit 0.11.1 under Mac, Yosemite (10.10), x64.

```
Mac-a8206651f7a4:hello_nodewebkit timothyha$ npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.11.1
npm WARN package.json Hello@ No repository field.
npm WARN package.json Hello@ No README data
-
> sqlite3@3.0.4 install /Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080701/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c:8645:26: warning: unused variable 'sqlite3one'
      [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:134:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/timothyha/.nw-gyp/0.11.1/deps/v8/include/v8.h:2116:8: note: candidate function not viable: requires 2
      arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/timothyha/.nw-gyp/0.11.1/deps/v8/include/v8.h:2118:8: note: candidate function not viable: requires 2
      arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:135:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/timothyha/.nw-gyp/0.11.1/deps/v8/include/v8.h:2116:8: note: candidate function not viable: requires 2
      arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/timothyha/.nw-gyp/0.11.1/deps/v8/include/v8.h:2118:8: note: candidate function not viable: requires 2
      arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:145:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:509:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:610:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings and 2 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node-webkit" "--node_abi=node-webkit-v0.11.1" "--target=0.11.1" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/lib/binding/node-webkit-v0.11.1-darwin-x64" "--module=/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/lib/binding/node-webkit-v0.11.1-darwin-x64/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package_name=node-webkit-v0.11.1-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.4/node-webkit-v0.11.1-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0.11.1-darwin-x64.tar.gz"
gyp ERR! cwd /Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3
gyp ERR! node -v v0.10.33
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node-webkit --node_abi=node-webkit-v0.11.1 --target=0.11.1 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/lib/binding/node-webkit-v0.11.1-darwin-x64 --module=/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/lib/binding/node-webkit-v0.11.1-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-webkit-v0.11.1-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-webkit-v0.11.1-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0.11.1-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Darwin 14.0.0
node-pre-gyp ERR! command "node" "/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.33
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node-webkit --node_abi=node-webkit-v0.11.1 --target=0.11.1 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/lib/binding/node-webkit-v0.11.1-darwin-x64 --module=/Users/timothyha/Projects/Node.js/hello_nodewebkit/node_modules/sqlite3/lib/binding/node-webkit-v0.11.1-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-webkit-v0.11.1-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-webkit-v0.11.1-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0.11.1-darwin-x64.tar.gz' (1)

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.11.1"
npm ERR! cwd /Users/timothyha/Projects/Node.js/hello_nodewebkit
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by premalatha-bv** [comment]
Any idea will this be working for nwjs 0.39.0 which is far latest now, then 0.10.x?

**Comment by premalatha-bv** [comment]
@springmeyer It is not working with latest version of nw i.e., 0.39.0 
Could you please help me. Please let me know, if it works or not. Am I wasting in trying to make it work?
