### ISSUE TITLE
Error using sqlite3 trying to build with sqlcipher

### ISSUE THREAD

**Issue by mkzaker** [mapbox/node-sqlite3#383]
Hi,
I was having problems building node-sqlite3 with sqlcipher on Opensuse 13.2 64bit.Use the following command its install without any error:
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/ 
Sqlcipher installed on /usr/local/lib64/
But I get the following error:
node test.js                    
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libsqlcipher.so.0: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ranis/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Help me please!

**Comment by springmeyer** [comment]
Try running `sudo ldconfig` or otherwise telling your system about the location of libsqlcipher.so. Basically this does not look like a node-sqlite3 problem as much as a problem with your sqlcipher install.

**Comment by mkzaker** [comment]
The problem was resolved by running the following command
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
Thanks
