### ISSUE TITLE
Failure to build 3.0.6 on ARM

### ISSUE THREAD

**Issue by Page-** [mapbox/node-sqlite3#445]
I'm getting this issue when trying to build 3.0.6 on nodejs 0.10.38 for ARM (using qemu): `/usr/bin/ld: Release/obj.target/node_sqlite3.node: No symbol version section for versioned symbol `memcpy@GLIBC_2.2.5'`

Full log:
```
npm install sqlite3
-
> sqlite3@3.0.6 install /usr/src/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory '/usr/src/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080900/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080900/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)':
../src/database.cc:145:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)':
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)':
../src/database.cc:509:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)':
../src/database.cc:610:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)':
../src/statement.cc:120:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:324:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:372:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:440:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:506:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:603:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:725:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
/usr/bin/ld: Release/obj.target/node_sqlite3.node: No symbol version section for versioned symbol `memcpy@GLIBC_2.2.5'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
node_sqlite3.target.mk:124: recipe for target 'Release/obj.target/node_sqlite3.node' failed
make: *** [Release/obj.target/node_sqlite3.node] Error 1
make: Leaving directory '/usr/src/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-27-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/src/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/src/node_modules/sqlite3/lib/binding/node-v11-linux-arm"
gyp ERR! cwd /usr/src/node_modules/sqlite3
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.13.0-27-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/src/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.38
node-pre-gyp ERR! node-pre-gyp -v v0.6.5
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
npm ERR! Linux 3.13.0-27-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/npm-debug.log
```

**Comment by forstermatth** [comment]
!
I'm getting the same errors when trying to build on iojs v1.8.1 using npm v2.8.3.

logs: https://gist.github.com/forstermatth/9a6584ed76d370b35dc6

**Comment by springmeyer** [comment]
@forstermatth - thanks for the report: can you confirm what operating system you are hitting this on? Ubuntu trusty 32 bit (from the looks of the hostname?)

**Comment by forstermatth** [comment]
Yes: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box

**Comment by forstermatth** [comment]
Confirming that `npm install sqlite3@3.0.5` works in my environment.

**Comment by springmeyer** [comment]
okay, I think I'm going to revert #444 and issue a new release (`v3.0.7`). I did not realize this would break support for any operating systems so it clearly needs more testing before being viable. /cc @bnoordhuis

**Comment by bnoordhuis** [comment]
I don't think that's necessary.  Looking at gcc-preinclude.h, it just needs an `#if defined(__i386__) || defined(__x86_64__)` guard.  I'll send a PR.

**Comment by springmeyer** [comment]
@bnoordhuis @forstermatth is on a i386 system I think. Any idea why it is breaking for him?

**Comment by bnoordhuis** [comment]
No.  I would have thought that the symbol name is the same.

@forstermatth Can you post the output of `nm build/Release/sqlite3.node | grep GLIBC` with v3.0.5?

**Comment by forstermatth** [comment]
I added it [to the gist](https://gist.github.com/forstermatth/9a6584ed76d370b35dc6#file-nm-outputs). 
I did the same thing with the x64 box out of curiosity, which looks like it has the right symbols.

**Comment by bnoordhuis** [comment]
Interesting, thanks.  I'll update the PR.

**Comment by springmeyer** [comment]
v3.0.7 is now published. @forstermatth - can you confirm this is fixed for you?

**Comment by Page-** [comment]
It's fixed for me

**Comment by springmeyer** [comment]
thanks for the followup @Page-

**Comment by forstermatth** [comment]
Confirmed.

**Comment by basarevych** [comment]
@springmeyer I am getting this error on FreeBSD x86_64 (GCC 4.8)

**Comment by bnoordhuis** [comment]
Gah, gcc-preinclude.h is included unconditionally.  I'll come up with another PR...

**Comment by lukehorvat** [comment]
I am encountering `warning: unused variable 'status' [-Wunused-variable]` on a Raspberry Pi when attempting to install sqlite3 v3.1.0. :( Anyone know what's up with that?
