### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by miguelmota** [mapbox/node-sqlite3#465]
```bash
root@moogs:/var/www/site# npm install sqlite3@latest                                                                                                                                                                                 
npm WARN package.json podcast-manager@1.0.0 No repository field.
npm http GET http://registry.npmjs.org/sqlite3
npm http 304 http://registry.npmjs.org/sqlite3
npm http GET http://registry.npmjs.org/nan
npm http GET http://registry.npmjs.org/node-pre-gyp
npm http 304 http://registry.npmjs.org/nan
npm http 304 http://registry.npmjs.org/node-pre-gyp

> sqlite3@3.0.8 install /var/www/site/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.13-linux-ia32.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.13-linux-ia32.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.13-linux-ia32.tar.gz (falling back to source compile with node-gyp) 
make: Entering directory `/var/www/site/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080900/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080900/sqlite3.o
virtual memory exhausted: Cannot allocate memory
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3080900/sqlite3.o] Error 1
make: Leaving directory `/var/www/site/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.2.0-24-virtual
gyp ERR! command "/root/.nvm/v0.11.13/bin/node" "/root/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/site/node_modules/sqlite3/lib/binding/node-v0.11.13-linux-ia32/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/www/site/node_modules/sqlite3/lib/binding/node-v0.11.13-linux-ia32"
gyp ERR! cwd /var/www/site/node_modules/sqlite3
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/v0.11.13/bin/node /root/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/site/node_modules/sqlite3/lib/binding/node-v0.11.13-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/site/node_modules/sqlite3/lib/binding/node-v0.11.13-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/site/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:992:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:5)
node-pre-gyp ERR! System Linux 3.2.0-24-virtual
node-pre-gyp ERR! command "node" "/var/www/site/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/site/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.11.13
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/root/.nvm/v0.11.13/bin/node /root/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/site/node_modules/sqlite3/lib/binding/node-v0.11.13-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/site/node_modules/sqlite3/lib/binding/node-v0.11.13-linux-ia32' (1)
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by springmeyer** [comment]
> virtual memory exhausted: Cannot allocate memory

^^ that is the relevant error. Looks like your machine is pretty small. And it looks like you are using node v0.11.x.

To solve this:

  - Use node v0.10.x or v0.12.x
  - Get a machine with more memory.
