### ISSUE TITLE
Failed to build manually

### ISSUE THREAD

**Issue by coolaj86** [mapbox/node-sqlite3#472]
Solution
=======

* [Building SQLCipher for node.js and Raspberry Pi](https://coolaj86.com/articles/building-sqlcipher-for-node-js-on-raspberry-pi-2/)
* [Building SQLCipher for OS X and node.js](https://coolaj86.com/articles/building-sqlcipher-on-os-x/)

Problem
=======

When I try to follow the directions in the README this is what I get:

```
export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local



\
> sqlite3@3.0.8 install /home/pi/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/pi/node_modules/sqlite3/build'
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:5:0:
../src/database.h:10:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
node_sqlite3.target.mk:93: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory '/home/pi/node_modules/sqlite3/build'
```

Yet we can see that `sqlite3.h` most certainly does exist:

```
ls /usr/local/include/sqlcipher/sqlite3.h
```

This is a leftover from https://github.com/mapbox/node-sqlite3/issues/413

**Comment by springmeyer** [comment]
Can you pass `--verbose` as well so we can see the compile args. My guess is that `-I/usr/local/include` is not ending up being passed to the compiler. You could try `export CXXFLAGS="-I/usr/local/include"` instead of CPPFLAGS.

**Comment by springmeyer** [comment]
Also try:  `export CPPFLAGS="-I/usr/local/include/sqlcipher/"`

**Comment by coolaj86** [comment]
```
export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include"
export CXXFLAGS="-I/usr/local/include"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose
```


```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/iojs',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'sqlite3',
npm verb cli   '--build-from-source',
npm verb cli   '--sqlite_libname=sqlcipher',
npm verb cli   '--sqlite=/usr/local',
npm verb cli   '--verbose' ]
npm info using npm@2.11.3
npm info using node@v2.3.1
npm verb config Skipping project config: /home/pi/.npmrc. (matches userconfig)
npm verb install initial load of /home/pi/package.json
npm verb readDependencies loading dependencies from /home/pi/package.json
npm verb cache add spec sqlite3
npm verb addNamed "*" is a valid semver range for sqlite3
npm verb addNameRange registry:https://registry.npmjs.org/sqlite3 not in flight; fetching
npm verb request uri https://registry.npmjs.org/sqlite3
npm verb request no auth needed
npm info attempt registry request try #1 at 21:35:00
npm verb request id acb08bf68542ce05
npm verb etag "7PI2ACROD9BM47CY9Z95DZZT6"
npm http request GET https://registry.npmjs.org/sqlite3
npm http 304 https://registry.npmjs.org/sqlite3
npm verb etag https://registry.npmjs.org/sqlite3 from cache
npm verb get saving sqlite3 to /home/pi/.npm/registry.npmjs.org/sqlite3/.cache.json
npm verb addNamed "3.0.8" is a plain semver version for sqlite3
npm verb afterAdd /home/pi/.npm/sqlite3/3.0.8/package/package.json not in flight; writing
npm verb afterAdd /home/pi/.npm/sqlite3/3.0.8/package/package.json written
npm info install sqlite3@3.0.8 into /home/pi
npm info installOne sqlite3@3.0.8
npm verb installOne of sqlite3 to /home/pi not in flight; installing
npm verb lock using /home/pi/.npm/_locks/sqlite3-47121c89ca36e8cc.lock for /home/pi/node_modules/sqlite3
npm verb unbuild node_modules/sqlite3
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3
npm verb tar unpack /home/pi/.npm/sqlite3/3.0.8/package.tgz
npm verb tar unpacking to /home/pi/node_modules/sqlite3
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3
npm verb write writing to /home/pi/node_modules/sqlite3/package.json
npm info preinstall sqlite3@3.0.8
npm verb readDependencies loading dependencies from /home/pi/node_modules/sqlite3/package.json
npm verb readDependencies loading dependencies from /home/pi/node_modules/sqlite3/package.json
npm verb targetResolver reading package data from /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/package.json
npm info package.json node-pre-gyp@0.6.7 license should be a valid SPDX license expression
npm verb cache add spec nan@~1.8.4
npm verb addNamed ">=1.8.4 <1.9.0" is a valid semver range for nan
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 21:35:15
npm verb etag "CWMZR9BQ6YD6KL99MGG0CU5U5"
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /home/pi/.npm/registry.npmjs.org/nan/.cache.json
npm verb addNamed "1.8.4" is a plain semver version for nan
npm verb afterAdd /home/pi/.npm/nan/1.8.4/package/package.json not in flight; writing
npm verb afterAdd /home/pi/.npm/nan/1.8.4/package/package.json written
npm verb installMany node-pre-gyp@0.6.7 was bundled with sqlite3@3.0.8
npm info install nan@1.8.4 into /home/pi/node_modules/sqlite3
npm info installOne nan@1.8.4
npm verb installOne of nan to /home/pi/node_modules/sqlite3 not in flight; installing
npm verb lock using /home/pi/.npm/_locks/nan-c0ecdbccbbd5b572.lock for /home/pi/node_modules/sqlite3/node_modules/nan
npm verb unbuild node_modules/sqlite3/node_modules/nan
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/nan
npm verb tar unpack /home/pi/.npm/nan/1.8.4/package.tgz
npm verb tar unpacking to /home/pi/node_modules/sqlite3/node_modules/nan
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/nan
npm verb write writing to /home/pi/node_modules/sqlite3/node_modules/nan/package.json
npm info preinstall nan@1.8.4
npm verb readDependencies loading dependencies from /home/pi/node_modules/sqlite3/node_modules/nan/package.json
npm verb readDependencies loading dependencies from /home/pi/node_modules/sqlite3/node_modules/nan/package.json
npm verb about to build /home/pi/node_modules/sqlite3/node_modules/nan
npm info build /home/pi/node_modules/sqlite3/node_modules/nan
npm info linkStuff nan@1.8.4
npm verb linkBins nan@1.8.4
npm verb linkMans nan@1.8.4
npm verb rebuildBundles nan@1.8.4
npm info install nan@1.8.4
npm info postinstall nan@1.8.4
npm verb unlock done using /home/pi/.npm/_locks/nan-c0ecdbccbbd5b572.lock for /home/pi/node_modules/sqlite3/node_modules/nan
npm verb about to build /home/pi/node_modules/sqlite3
npm info build /home/pi/node_modules/sqlite3
npm info linkStuff sqlite3@3.0.8
npm verb linkBins sqlite3@3.0.8
npm verb linkMans sqlite3@3.0.8
npm verb rebuildBundles sqlite3@3.0.8
npm verb rebuildBundles [ 'nan', 'node-pre-gyp' ]
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp
npm info preinstall node-pre-gyp@0.6.7
npm info linkStuff node-pre-gyp@0.6.7
npm verb linkBins node-pre-gyp@0.6.7
npm verb link bins [ { 'node-pre-gyp': './bin/node-pre-gyp' },
npm verb link bins   '/home/pi/node_modules/sqlite3/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans node-pre-gyp@0.6.7
npm verb rebuildBundles node-pre-gyp@0.6.7
npm verb rebuildBundles [ 'mkdirp',
npm verb rebuildBundles   'nopt',
npm verb rebuildBundles   'npmlog',
npm verb rebuildBundles   'rc',
npm verb rebuildBundles   'request',
npm verb rebuildBundles   'rimraf',
npm verb rebuildBundles   'semver',
npm verb rebuildBundles   'tar',
npm verb rebuildBundles   'tar-pack' ]
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/.bin/node-pre-gyp
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp
npm info preinstall mkdirp@0.5.0
npm info linkStuff mkdirp@0.5.0
npm verb linkBins mkdirp@0.5.0
npm verb link bins [ { mkdirp: 'bin/cmd.js' },
npm verb link bins   '/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans mkdirp@0.5.0
npm verb rebuildBundles mkdirp@0.5.0
npm verb rebuildBundles [ 'minimist' ]
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin/mkdirp
npm info install mkdirp@0.5.0
npm info postinstall mkdirp@0.5.0
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/nopt
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/nopt
npm info preinstall nopt@3.0.1
npm info linkStuff nopt@3.0.1
npm verb linkBins nopt@3.0.1
npm verb link bins [ { nopt: './bin/nopt.js' },
npm verb link bins   '/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans nopt@3.0.1
npm verb rebuildBundles nopt@3.0.1
npm verb rebuildBundles [ 'abbrev' ]
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin/nopt
npm info install nopt@3.0.1
npm info postinstall nopt@3.0.1
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog
npm info preinstall npmlog@1.2.0
npm info linkStuff npmlog@1.2.0
npm verb linkBins npmlog@1.2.0
npm verb linkMans npmlog@1.2.0
npm verb rebuildBundles npmlog@1.2.0
npm verb rebuildBundles [ 'ansi', 'are-we-there-yet', 'gauge' ]
npm info install npmlog@1.2.0
npm info postinstall npmlog@1.2.0
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rc
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rc
npm info preinstall rc@1.0.1
npm info linkStuff rc@1.0.1
npm verb linkBins rc@1.0.1
npm verb link bins [ { rc: './index.js' },
npm verb link bins   '/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans rc@1.0.1
npm verb rebuildBundles rc@1.0.1
npm verb rebuildBundles [ 'deep-extend', 'ini', 'minimist', 'strip-json-comments' ]
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin/rc
npm info install rc@1.0.1
npm info postinstall rc@1.0.1
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/request
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/request
npm info preinstall request@2.55.0
npm info linkStuff request@2.55.0
npm verb linkBins request@2.55.0
npm verb linkMans request@2.55.0
npm verb rebuildBundles request@2.55.0
npm verb rebuildBundles [ 'aws-sign2',
npm verb rebuildBundles   'bl',
npm verb rebuildBundles   'caseless',
npm verb rebuildBundles   'combined-stream',
npm verb rebuildBundles   'forever-agent',
npm verb rebuildBundles   'form-data',
npm verb rebuildBundles   'har-validator',
npm verb rebuildBundles   'hawk',
npm verb rebuildBundles   'http-signature',
npm verb rebuildBundles   'isstream',
npm verb rebuildBundles   'json-stringify-safe',
npm verb rebuildBundles   'mime-types',
npm verb rebuildBundles   'node-uuid',
npm verb rebuildBundles   'oauth-sign',
npm verb rebuildBundles   'qs',
npm verb rebuildBundles   'stringstream',
npm verb rebuildBundles   'tough-cookie',
npm verb rebuildBundles   'tunnel-agent' ]
npm info install request@2.55.0
npm info postinstall request@2.55.0
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rimraf
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rimraf
npm info preinstall rimraf@2.3.3
npm info linkStuff rimraf@2.3.3
npm verb linkBins rimraf@2.3.3
npm verb link bins [ { rimraf: './bin.js' },
npm verb link bins   '/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans rimraf@2.3.3
npm verb rebuildBundles rimraf@2.3.3
npm verb rebuildBundles [ 'glob' ]
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin/rimraf
npm info install rimraf@2.3.3
npm info postinstall rimraf@2.3.3
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/semver
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/semver
npm info preinstall semver@4.3.3
npm info linkStuff semver@4.3.3
npm verb linkBins semver@4.3.3
npm verb link bins [ { semver: './bin/semver' },
npm verb link bins   '/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans semver@4.3.3
npm verb rebuildBundles semver@4.3.3
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/.bin/semver
npm info install semver@4.3.3
npm info postinstall semver@4.3.3
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar
npm info preinstall tar@2.1.0
npm info linkStuff tar@2.1.0
npm verb linkBins tar@2.1.0
npm verb linkMans tar@2.1.0
npm verb rebuildBundles tar@2.1.0
npm verb rebuildBundles [ 'block-stream', 'fstream', 'inherits' ]
npm info install tar@2.1.0
npm info postinstall tar@2.1.0
npm verb rebuild bundle /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack
npm info build /home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack
npm info preinstall tar-pack@2.0.0
npm info linkStuff tar-pack@2.0.0
npm verb linkBins tar-pack@2.0.0
npm verb linkMans tar-pack@2.0.0
npm verb rebuildBundles tar-pack@2.0.0
npm verb rebuildBundles [ 'debug',
npm verb rebuildBundles   'fstream',
npm verb rebuildBundles   'fstream-ignore',
npm verb rebuildBundles   'graceful-fs',
npm verb rebuildBundles   'once',
npm verb rebuildBundles   'readable-stream',
npm verb rebuildBundles   'rimraf',
npm verb rebuildBundles   'tar',
npm verb rebuildBundles   'uid-number' ]
npm info install tar-pack@2.0.0
npm info postinstall tar-pack@2.0.0
npm info install node-pre-gyp@0.6.7
npm info postinstall node-pre-gyp@0.6.7
npm info install sqlite3@3.0.8

> sqlite3@3.0.8 install /home/pi/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/iojs',
node-pre-gyp verb cli   '/home/pi/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.7
node-pre-gyp info using node@2.3.1 | linux | arm
node-pre-gyp verb command install []
node-pre-gyp info build requesting source compile
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/iojs',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean' ]
gyp info using node-gyp@2.0.1
gyp info using node@2.3.1 | linux | arm
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/iojs',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm' ]
gyp info using node-gyp@2.0.1
gyp info using node@2.3.1 | linux | arm
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
gyp verb get node dir no --target version specified, falling back to host node version: v2.3.1
gyp verb command install [ 'v2.3.1' ]
gyp verb install input version string "v2.3.1"
gyp verb install installing version: 2.3.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 2.3.1
gyp verb build dir attempting to create "build" dir: /home/pi/node_modules/sqlite3/build
gyp verb build dir "build" dir needed to be created? /home/pi/node_modules/sqlite3/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/pi/node_modules/sqlite3/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/pi/node_modules/sqlite3/config.gypi
gyp verb common.gypi checking for gypi file: /home/pi/node_modules/sqlite3/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.node-gyp/2.3.1/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/2.3.1',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/iojs',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm' ]
gyp info using node-gyp@2.0.1
gyp info using node@2.3.1 | linux | arm
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /home/pi/.node-gyp/2.3.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/node_modules/sqlite3/build'
  g++ '-DNODE_GYP_MODULE_NAME=node_sqlite3' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' '-DNDEBUG' -I/home/pi/.node-gyp/2.3.1/src -I/home/pi/.node-gyp/2.3.1/deps/uv/include -I/home/pi/.node-gyp/2.3.1/deps/v8/include -I../node_modules/nan -I/usr/local/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -include ../src/gcc-preinclude.h -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/node_sqlite3/src/database.o.d.raw -I/usr/local/include -c -o Release/obj.target/node_sqlite3/src/database.o ../src/database.cc
In file included from ../src/database.cc:5:0:
../src/database.h:10:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
node_sqlite3.target.mk:93: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory '/home/pi/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm"
gyp ERR! cwd /home/pi/node_modules/sqlite3
gyp ERR! node -v v2.3.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/iojs /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:764:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.18.11-v7+
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/home/pi/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/node_modules/sqlite3
node-pre-gyp ERR! node -v v2.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/iojs /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v44-linux-arm' (1)
npm verb unsafe-perm in lifecycle true
npm info sqlite3@3.0.8 Failed to exec install script
npm verb unlock done using /home/pi/.npm/_locks/sqlite3-47121c89ca36e8cc.lock for /home/pi/node_modules/sqlite3
npm verb stack Error: sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:764:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid sqlite3@3.0.8
npm verb cwd /home/pi
npm ERR! Linux 3.18.11-v7+
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source" "--sqlite_libname=sqlcipher" "--sqlite=/usr/local" "--verbose"
npm ERR! node v2.3.1
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/sqlite3
npm info preuninstall sqlite3@3.0.8
npm info uninstall sqlite3@3.0.8
npm verb unbuild rmStuff sqlite3@3.0.8 from /home/pi/node_modules
npm info postuninstall sqlite3@3.0.8
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```

**Comment by coolaj86** [comment]
I got a little bit further:

```bash
export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
export CXXFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose

node -e 'require("sqlite3")'
```

```
module.js:353
  Module._extensions[extension](this, filename);
                               ^
Error: libsqlcipher.so.0: cannot open shared object file: No such file or directory
    at Error (native)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/pi/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

And yet again `/usr/local/lib/libsqlcipher.so.0` very much exists.

**Comment by coolaj86** [comment]
Ah, I forgot `sudo ldconfig` after `make install` of sqlcipher itself.

**Comment by coolaj86** [comment]
This can be closed when the pull request is accepted.

**Comment by springmeyer** [comment]
#473
