### ISSUE TITLE
sqlite3 install error - node-pre-gyp: not found

### ISSUE THREAD

**Issue by shaunthomas999** [mapbox/node-sqlite3#474]
Hi,

I have a package.json file which has following dependencies:
```javascript
"dependencies": {
    "body-parser": "^1.9.0",
    "deasync": "^0.0.10",
    "exec-sync": "^0.1.6",
    "express": "^4.9.5",
    "libxmljs": "^0.13.0",
    "mongodb": "^1.4.31",
    "mysql": "^2.5.1",
    "segfault-handler": "^0.2.4",
    "sqlite3": "^3.0.0",
    "underscore": "^1.7.0",
    "webworker-threads": "^0.5.5",
    "winston": "^1.0.0"
  }
```
I get the following error when doing `npm install`
```
npm info install node-pre-gyp@0.6.7
npm info postinstall node-pre-gyp@0.6.7
npm info install sqlite3@3.0.8

> sqlite3@3.0.8 install /tmp/hub_node_modules/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found
npm verb unsafe-perm in lifecycle false
npm info sqlite3@3.0.8 Failed to exec install script
npm verb unlock done using /usr/local/nonroot/.npm/_locks/sqlite3-8f1b2b4d6261ee24.lock for /tmp/hub_node_modules/node_modules/sqlite3
npm verb stack Error: sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm verb stack spawn ENOENT
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
npm verb stack     at ChildProcess.emit (events.js:98:17)
npm verb stack     at maybeClose (child_process.js:766:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm verb pkgid sqlite3@3.0.8
npm verb cwd /tmp/hub_node_modules
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-ddd"
npm ERR! node v0.10.39
npm ERR! npm  v2.12.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/sqlite3
npm info preuninstall sqlite3@3.0.8
npm info uninstall sqlite3@3.0.8
```
How can I solve this problem? More detailed logs in the gist > https://gist.github.com/shaunthomas999/ea2e90754804441c5be3

**Comment by shaunthomas999** [comment]
I have some additional information. I am using Ubuntu 14.04 OS and the above issue is happening when building a Docker image, which has Ubuntu 14.04 as base, from a Dockerfile. node location is /usr/local/bin/node. Nodejs version 0.10.39 and Npm version is 2.12.1. The same issue exists with Nodejs version 0.10.38 and Npm version 2.11.3 and 2.12.0.

**Comment by springmeyer** [comment]
This will happen if you run as root. Either don't run as root or pass `--unsafe-perm`. More details at https://github.com/mapbox/node-pre-gyp/issues/165.

**Comment by mageddo** [comment]
Version 4.0 is not complatible yet and reproduce this same error
