### ISSUE TITLE
npm ERR! Failed at the sqlite3@3.0.9 install script 'node-pre-gyp install --fallback-to-build'.

### ISSUE THREAD

**Issue by TascSystems** [mapbox/node-sqlite3#485]
Installing on Debian/ARM system - I was able to do this successfully on v3.0.5, but appears to fail in this new version. Let me know if you need more info.

```
npm WARN package.json sitersm-net@1.0.0 No repository field.
npm WARN package.json sitersm-net@1.0.0 No README data
|
> sqlite3@3.0.9 install /home/debian/webapp/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/debian/webapp/node_modules/sqlite3/.node-gyp"
make: Entering directory `/home/debian/webapp/node_modules/sqlite3/build'
make: *** No rule to make target `../.node-gyp/0.12.7/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/home/debian/webapp/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.14.1_006-trio2000
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/debian/webapp/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/debian/webapp/node_modules/sqlite3/lib/binding/node-v14-linux-arm"
gyp ERR! cwd /home/debian/webapp/node_modules/sqlite3
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/debian/webapp/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/debian/webapp/node_modules/sqlite3/lib/binding/node-v14-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/debian/webapp/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.14.1_006-trio2000
node-pre-gyp ERR! command "node" "/home/debian/webapp/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/debian/webapp/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.8
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/debian/webapp/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/debian/webapp/node_modules/sqlite3/lib/binding/node-v14-linux-arm' (1)
npm ERR! Linux 3.14.1_006-trio2000
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.9 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/debian/webapp/npm-debug.log
```

**Comment by TascSystems** [comment]
Just confirmed that v3.0.5 appears to install on my system.

**Comment by springmeyer** [comment]
the problem is you are building as root. Don't do that, or use `--unsafe-per`. More details at https://github.com/mapbox/node-pre-gyp/issues/165

**Comment by imZack** [comment]
Oh god, the error message is just so unclear :scream:
