### ISSUE TITLE
Undefined variable module_name in binding.gyp

### ISSUE THREAD

**Issue by s-a** [mapbox/node-sqlite3#491]
I try to compile against atom shell.

ref: https://github.com/s-a/iron-node/issues/42

```shell
node-gyp rebuild --target=0.30.2 --arch=ia32 --dist-url=https://atom.io/download/atom-shell

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.12.6 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.30.2/node-v0.30.2.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.30.2/node-v0.30.2.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.30.2/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v0.30.2/node.lib
gyp http GET https://atom.io/download/atom-shell/v0.30.2/x64/node.lib
gyp http 200 https://atom.io/download/atom-shell/v0.30.2/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v0.30.2/node.lib
gyp http 200 https://atom.io/download/atom-shell/v0.30.2/x64/node.lib
gyp info spawn c:\python27\python.exe
gyp info spawn args [ 'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\git\\electron-recompile\\tmp\\sqlite3@3.0.10\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\git\\electron-recompile\\tmp\\sqlite3@3.0.10\\electron-gyp \\.node-gyp\\0.30.2\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=c:\\git\\electron-recompile\\tmp\\sqlite3@3.0.10\\electron-gyp \\.node-gyp\\0.30.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dmodule_root_dir=c:\\git\\electron-recompile\\tmp\\sqlite3@3.0.10',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\git\\electron-recompile\\tmp\\sqlite3@3.0.10\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Stephan\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.30.2" "--arch=ia32" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd c:\git\electron-recompile\tmp\sqlite3@3.0.10
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
Failed to compile : sqlite3
```

**Comment by Steviey** [comment]
+1 gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
