### ISSUE TITLE
Fails to run on Node v4.0.0 -- binary module installed in wrong directory

### ISSUE THREAD

**Issue by robogeek** [mapbox/node-sqlite3#504]
npm install works correctly .. package.json says

```
dependencies: { ... "sqlite3": "*", ... }
```

When running my app it fails with this error

```
Error: Cannot find module '/Volumes/Drobo5N/drb142101a00015/1/David/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/Drobo5N/drb142101a00015/1/David/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I notice that the directory /Volumes/Drobo5N/drb142101a00015/1/David/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/ does not exist.  Instead a directory of a somewhat different name is built.

```
tippy:notes davidherron$ ls node_modules/sqlite3/lib/binding/
node-v14-darwin-x64
```

During the npm install step I see this message:

```
> sqlite3@3.0.10 install /Volumes/Drobo5N/drb142101a00015/1/David/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Volumes/Drobo5N/drb142101a00015/1/David/NodeWebDevelopment/book-rev2/filez/chap06/notes/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node" is installed via remote
```

**Comment by springmeyer** [comment]
Try upgrading to `sqlite3@3.1.0` (just released) which should fix this problem.

**Comment by robogeek** [comment]
Yes upgraded to 3.1.0 and now it works.  Also I did this:

```
$ export PATH=/usr/local/node-v4.0.0-linux-x64/bin:${PATH}
```

So that the correct node binary is on the PATH .. and that had helped with some other problem.
