### ISSUE TITLE
Install failed from Ubuntu 15.04 and Node.js 4.1.1

### ISSUE THREAD

**Issue by DCKT** [mapbox/node-sqlite3#519]
Hi,

I tried to install the package from Ubuntu 15.04 and Node.js 4.1.1 but it failed.
Here is the log : 

```
make: Entering directory '/var/www/blog/node_modules/node-sqlite3/build'
  CXX(target) Release/obj.target/node_sqlite3/src/third_party/CodingConv/encodeutil.o
../src/third_party/CodingConv/encodeutil.cpp: In static member function ‘static std::string encodeConv::CodingConv::Unicode2Utf8(const wchar_t*)’:
../src/third_party/CodingConv/encodeutil.cpp:129:6: warning: variable ‘bytes’ set but not used [-Wunused-but-set-variable]
  int bytes = 0;
      ^
  CXX(target) Release/obj.target/node_sqlite3/src/nodejs/Sqlite3Client.o
In file included from ../src/nodejs/Sqlite3Client.cpp:2:0:
../src/nodejs/Sqlite3Client.h:12:1: error: expected class-name before ‘{’ token
 {
 ^
../src/nodejs/Sqlite3Client.h:15:32: error: ‘Arguments’ does not name a type
  static Handle<Value>New(const Arguments& args);
                                ^
../src/nodejs/Sqlite3Client.h:16:33: error: ‘Arguments’ does not name a type
  static Handle<Value>Open(const Arguments& args);
                                 ^
../src/nodejs/Sqlite3Client.h:17:35: error: ‘Arguments’ does not name a type
  static Handle<Value>IsOpen(const Arguments& args);
                                   ^
../src/nodejs/Sqlite3Client.h:18:23: error: ‘uv_work_t’ has not been declared
  static void EIO_Open(uv_work_t* req);
                       ^
../src/nodejs/Sqlite3Client.h:19:28: error: ‘uv_work_t’ has not been declared
  static void EIO_AfterOpen(uv_work_t* req, int status);
                            ^
../src/nodejs/Sqlite3Client.h:20:33: error: ‘uv_async_t’ has not been declared
  static void open_asyn_callback(uv_async_t* handle, int status);
                                 ^
../src/nodejs/Sqlite3Client.h:21:37: error: ‘Arguments’ does not name a type
  static Handle<Value>OpenSync(const Arguments& args);
                                     ^
In file included from ../src/sqlite3_encrypt/platform_config.h:32:0,
                 from ../src/sqlite3_encrypt/DbSqlite.h:4,
                 from ../src/nodejs/Sqlite3Connection.h:7,
                 from ../src/nodejs/Sqlite3Client.cpp:3:
../src/sqlite3_encrypt/sqlite3_def.h:95:32: note: #pragma message: MCBS Selected
 #pragma message("MCBS Selected")
                                ^
In file included from ../src/nodejs/Sqlite3Client.cpp:3:0:
../src/nodejs/Sqlite3Connection.h:11:1: error: expected class-name before ‘{’ token
 {
 ^
../src/nodejs/Sqlite3Connection.h:15:33: error: ‘Arguments’ does not name a type
  static Handle<Value> New(const Arguments& args);
                                 ^
../src/nodejs/Sqlite3Connection.h:17:34: error: ‘Arguments’ does not name a type
  static Handle<Value>Close(const Arguments& args);
                                  ^
../src/nodejs/Sqlite3Connection.h:18:34: error: ‘Arguments’ does not name a type
  static Handle<Value>Query(const Arguments& args);
                                  ^
../src/nodejs/Sqlite3Connection.h:19:36: error: ‘Arguments’ does not name a type
  static Handle<Value>Execute(const Arguments& args);
                                    ^
../src/nodejs/Sqlite3Connection.h:20:40: error: ‘Arguments’ does not name a type
  static Handle<Value>ExecuteSync(const Arguments& args);
                                        ^
../src/nodejs/Sqlite3Connection.h:21:37: error: ‘Arguments’ does not name a type
  static Handle<Value>EnterKey(const Arguments& args);
                                     ^
../src/nodejs/Sqlite3Connection.h:22:35: error: ‘Arguments’ does not name a type
  static Handle<Value>DelKey(const Arguments& args);
                                   ^
../src/nodejs/Sqlite3Connection.h:23:38: error: ‘Arguments’ does not name a type
  static Handle<Value>ChangeKey(const Arguments& args);
                                      ^
../src/nodejs/Sqlite3Connection.h:24:39: error: ‘Arguments’ does not name a type
  static Handle<Value>BeginTrans(const Arguments& args);
                                       ^
../src/nodejs/Sqlite3Connection.h:25:42: error: ‘Arguments’ does not name a type
  static Handle<Value>RollbackTrans(const Arguments& args);
                                          ^
../src/nodejs/Sqlite3Connection.h:26:40: error: ‘Arguments’ does not name a type
  static Handle<Value>CommitTrans(const Arguments& args);
                                        ^
../src/nodejs/Sqlite3Connection.h:27:35: error: ‘Arguments’ does not name a type
  static Handle<Value>IsOpen(const Arguments& args);
                                   ^
../src/nodejs/Sqlite3Connection.h:28:41: error: ‘Arguments’ does not name a type
  static Handle<Value>GetLastError(const Arguments& args);
                                         ^
../src/nodejs/Sqlite3Connection.h:40:41: error: ‘uv_async_t’ has not been declared
  static void query_asyn_thread_callback(uv_async_t* req,int status);
                                         ^
../src/nodejs/Sqlite3Connection.h:42:28: error: ‘uv_handle_t’ has not been declared
  static void uv_close_func(uv_handle_t* handle);
                            ^
../src/nodejs/Sqlite3Connection.h:43:35: error: ‘uv_async_t’ has not been declared
  static void excute_asyn_callback(uv_async_t* handle, int status);
                                   ^
../src/nodejs/Sqlite3Connection.h:44:25: error: ‘uv_work_t’ has not been declared
  static void uv_execute(uv_work_t* req);
                         ^
../src/nodejs/Sqlite3Connection.h:45:31: error: ‘uv_work_t’ has not been declared
  static void uv_execute_after(uv_work_t* req,int status);
                               ^
../src/nodejs/Sqlite3Connection.h:46:23: error: ‘uv_work_t’ has not been declared
  static void uv_query(uv_work_t* req);
                       ^
../src/nodejs/Sqlite3Connection.h:47:29: error: ‘uv_work_t’ has not been declared
  static void uv_query_after(uv_work_t* req,int status);
                             ^
In file included from ../src/nodejs/Sqlite3Client.cpp:4:0:
../src/nodejs/ConnJob.h:30:2: error: ‘uv_work_t’ does not name a type
  uv_work_t req;
  ^
../src/nodejs/ConnJob.h:31:2: error: ‘uv_async_t’ does not name a type
  uv_async_t main_async;
  ^
In file included from ../src/nodejs/Sqlite3Client.cpp:5:0:
../src/nodejs/Statement.h:10:1: error: expected class-name before ‘{’ token
 {
 ^
../src/nodejs/Statement.h:16:33: error: ‘Arguments’ does not name a type
  static Handle<Value> New(const Arguments& args);
                                 ^
../src/nodejs/Statement.h:17:39: error: ‘Arguments’ does not name a type
  static Handle<Value> MoveFirst(const Arguments& args);
                                       ^
../src/nodejs/Statement.h:18:38: error: ‘Arguments’ does not name a type
  static Handle<Value> MoveNext(const Arguments& args);
                                      ^
../src/nodejs/Statement.h:19:38: error: ‘Arguments’ does not name a type
  static Handle<Value> MoveLast(const Arguments& args);
                                      ^
../src/nodejs/Statement.h:20:43: error: ‘Arguments’ does not name a type
  static Handle<Value> GetFieldCount(const Arguments& args);
                                           ^
../src/nodejs/Statement.h:21:44: error: ‘Arguments’ does not name a type
  static Handle<Value> GetRecordCount(const Arguments& args);
                                            ^
../src/nodejs/Statement.h:22:50: error: ‘Arguments’ does not name a type
  static Handle<Value> GetFieldValueByIndex(const Arguments& args);
                                                  ^
../src/nodejs/Statement.h:23:49: error: ‘Arguments’ does not name a type
  static Handle<Value> GetFieldValueByName(const Arguments& args);
                                                 ^
../src/nodejs/Statement.h:24:42: error: ‘Arguments’ does not name a type
  static Handle<Value> GetFieldName(const Arguments& args);
                                          ^
In file included from ../src/nodejs/Sqlite3Client.cpp:7:0:
../src/nodejs/NodeFunction.h:13:25: error: ‘Arguments’ does not name a type
  TSTRING MergeSql(const Arguments&args);
                         ^
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h: In static member function ‘static void Sqlite3Client::Init(v8::Handle<v8::Object>)’:
/root/.node-gyp/4.1.1/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/nodejs/Sqlite3Client.cpp:19:14: error: within this context
  HandleScope scope;
              ^
../src/nodejs/Sqlite3Client.cpp:21:55: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
  Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                       ^
../src/nodejs/Sqlite3Client.cpp:21:55: note: candidate is:
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:4349:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/4.1.1/include/node/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/nodejs/Sqlite3Client.cpp:22:44: error: no matching function for call to ‘v8::Persistent<v8::FunctionTemplate>::New(v8::Local<v8::FunctionTemplate>&)’
  s_ct = Persistent<FunctionTemplate>::New(t);
                                            ^
../src/nodejs/Sqlite3Client.cpp:22:44: note: candidate is:
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:7168:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::FunctionTemplate]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/4.1.1/include/node/v8.h:7168:4: note:   candidate expects 2 arguments, 1 provided
../src/nodejs/Sqlite3Client.cpp:23:6: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
  s_ct->InstanceTemplate()->SetInternalFieldCount(1);
      ^
../src/nodejs/Sqlite3Client.cpp:24:6: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
  s_ct->SetClassName(String::NewSymbol("Sqlite3Client"));  //名字就是以后new 的类型
      ^
../src/nodejs/Sqlite3Client.cpp:24:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
  s_ct->SetClassName(String::NewSymbol("Sqlite3Client"));  //名字就是以后new 的类型
                     ^
../src/nodejs/Sqlite3Client.cpp:28:30: error: ‘NewSymbol’ is not a member of ‘v8::String’
  t->PrototypeTemplate()->Set(String::NewSymbol("open"),
                              ^
../src/nodejs/Sqlite3Client.cpp:29:33: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
       FunctionTemplate::New(Open)->GetFunction());
                                 ^
../src/nodejs/Sqlite3Client.cpp:29:33: note: candidate is:
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:4349:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/4.1.1/include/node/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/nodejs/Sqlite3Client.cpp:30:30: error: ‘NewSymbol’ is not a member of ‘v8::String’
  t->PrototypeTemplate()->Set(String::NewSymbol("openSync"),
                              ^
../src/nodejs/Sqlite3Client.cpp:31:33: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   FunctionTemplate::New(OpenSync)->GetFunction());
                                 ^
../src/nodejs/Sqlite3Client.cpp:31:33: note: candidate is:
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:4349:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/4.1.1/include/node/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/nodejs/Sqlite3Client.cpp:32:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
  target->Set(String::NewSymbol("Sqlite3Client"), s_ct->GetFunction());
              ^
../src/nodejs/Sqlite3Client.cpp:32:54: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
  target->Set(String::NewSymbol("Sqlite3Client"), s_ct->GetFunction());
                                                      ^
../src/nodejs/Sqlite3Client.cpp: At global scope:
../src/nodejs/Sqlite3Client.cpp:36:40: error: ‘Arguments’ does not name a type
 Handle<Value> Sqlite3Client::New(const Arguments& args) {
                                        ^
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h: In static member function ‘static v8::Handle<v8::Value> Sqlite3Client::New(const int&)’:
/root/.node-gyp/4.1.1/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/nodejs/Sqlite3Client.cpp:37:14: error: within this context
  HandleScope scope;
              ^
../src/nodejs/Sqlite3Client.cpp:39:10: error: ‘class Sqlite3Client’ has no member named ‘Wrap’
  client->Wrap(args.This());
          ^
../src/nodejs/Sqlite3Client.cpp:39:20: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
  client->Wrap(args.This());
                    ^
../src/nodejs/Sqlite3Client.cpp:40:14: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
  return args.This();
              ^
../src/nodejs/Sqlite3Client.cpp: At global scope:
../src/nodejs/Sqlite3Client.cpp:44:41: error: ‘Arguments’ does not name a type
 Handle<Value> Sqlite3Client::Open(const Arguments& args) {
                                         ^
../src/nodejs/Sqlite3Client.cpp: In static member function ‘static v8::Handle<v8::Value> Sqlite3Client::Open(const int&)’:
../src/nodejs/Sqlite3Client.cpp:45:26: error: ‘ObjectWrap’ has not been declared
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                          ^
../src/nodejs/Sqlite3Client.cpp:45:58: error: expected primary-expression before ‘>’ token
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                                                          ^
../src/nodejs/Sqlite3Client.cpp:45:65: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                                                                 ^
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/nodejs/Sqlite3Client.cpp:46:14: error: within this context
  HandleScope scope;
              ^
../src/nodejs/Sqlite3Client.cpp:47:34: error: invalid types ‘const int[int]’ for array subscript
  String::Utf8Value strPath(args[0]);
                                  ^
../src/nodejs/Sqlite3Client.cpp:55:54: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
  connJob->js_obj = Persistent<Object>::New(args[args.Length()-1]->ToObject());
                                                      ^
../src/nodejs/Sqlite3Client.cpp:57:11: error: ‘class ConnJob’ has no member named ‘main_async’
  connJob->main_async.data = connJob;
           ^
../src/nodejs/Sqlite3Client.cpp:58:32: error: ‘uv_default_loop’ was not declared in this scope
  uv_async_init(uv_default_loop(),&connJob->main_async,open_asyn_callback);
                                ^
../src/nodejs/Sqlite3Client.cpp:58:44: error: ‘class ConnJob’ has no member named ‘main_async’
  uv_async_init(uv_default_loop(),&connJob->main_async,open_asyn_callback);
                                            ^
../src/nodejs/Sqlite3Client.cpp:58:73: error: ‘uv_async_init’ was not declared in this scope
  uv_async_init(uv_default_loop(),&connJob->main_async,open_asyn_callback);
                                                                         ^
../src/nodejs/Sqlite3Client.cpp:61:26: error: ‘class ConnJob’ has no member named ‘main_async’
  uv_async_send(&connJob->main_async);
                          ^
../src/nodejs/Sqlite3Client.cpp:61:36: error: ‘uv_async_send’ was not declared in this scope
  uv_async_send(&connJob->main_async);
                                    ^
../src/nodejs/Sqlite3Client.cpp:63:19: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
  return Undefined();
                   ^
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:315:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/nodejs/Sqlite3Client.cpp: At global scope:
../src/nodejs/Sqlite3Client.cpp:66:44: error: ‘Arguments’ does not name a type
 Handle<Value>Sqlite3Client::OpenSync(const Arguments& args)
                                            ^
../src/nodejs/Sqlite3Client.cpp: In static member function ‘static v8::Handle<v8::Value> Sqlite3Client::OpenSync(const int&)’:
../src/nodejs/Sqlite3Client.cpp:68:26: error: ‘ObjectWrap’ has not been declared
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                          ^
../src/nodejs/Sqlite3Client.cpp:68:58: error: expected primary-expression before ‘>’ token
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                                                          ^
../src/nodejs/Sqlite3Client.cpp:68:65: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                                                                 ^
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/nodejs/Sqlite3Client.cpp:69:14: error: within this context
  HandleScope scope;
              ^
../src/nodejs/Sqlite3Client.cpp:71:34: error: invalid types ‘const int[int]’ for array subscript
  String::Utf8Value strPath(args[0]);
                                  ^
../src/nodejs/Sqlite3Client.cpp:82:69: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
   Handle<Object> connection = Sqlite3Connection::constructorTemplate->GetFunction()->NewInstance();
                                                                     ^
../src/nodejs/Sqlite3Client.cpp:83:10: error: ‘node::ObjectWrap’ has not been declared
   (node::ObjectWrap::Unwrap<Sqlite3Connection>(connection))->setConnection(pConn);
          ^
../src/nodejs/Sqlite3Client.cpp:83:46: error: expected primary-expression before ‘>’ token
   (node::ObjectWrap::Unwrap<Sqlite3Connection>(connection))->setConnection(pConn);
                                              ^
../src/nodejs/Sqlite3Client.cpp:90:21: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
   argv[0]=Undefined();
                     ^
In file included from ../src/nodejs/Sqlite3Client.h:4:0,
                 from ../src/nodejs/Sqlite3Client.cpp:2:
/root/.node-gyp/4.1.1/include/node/v8.h:315:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/nodejs/Sqlite3Client.cpp:94:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(argv[0]);
               ^
../src/nodejs/Sqlite3Client.cpp:68:17: warning: unused variable ‘client’ [-Wunused-variable]
  Sqlite3Client* client = ObjectWrap::Unwrap<Sqlite3Client>(args.This());
                 ^
../src/nodejs/Sqlite3Client.cpp: At global scope:
../src/nodejs/Sqlite3Client.cpp:98:40: error: variable or field ‘open_asyn_callback’ declared void
 void Sqlite3Client::open_asyn_callback(uv_async_t* handle, int status)
                                        ^
../src/nodejs/Sqlite3Client.cpp:98:40: error: ‘uv_async_t’ was not declared in this scope
../src/nodejs/Sqlite3Client.cpp:98:52: error: ‘handle’ was not declared in this scope
 void Sqlite3Client::open_asyn_callback(uv_async_t* handle, int status)
                                                    ^
../src/nodejs/Sqlite3Client.cpp:98:60: error: expected primary-expression before ‘int’
 void Sqlite3Client::open_asyn_callback(uv_async_t* handle, int status)
                                                            ^
../src/nodejs/Sqlite3Client.cpp: In static member function ‘static v8::Handle<v8::Value> Sqlite3Client::New(const int&)’:
../src/nodejs/Sqlite3Client.cpp:41:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/nodejs/Sqlite3Client.cpp: In static member function ‘static v8::Handle<v8::Value> Sqlite3Client::Open(const int&)’:
../src/nodejs/Sqlite3Client.cpp:64:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/nodejs/Sqlite3Client.cpp: In static member function ‘static v8::Handle<v8::Value> Sqlite3Client::OpenSync(const int&)’:
../src/nodejs/Sqlite3Client.cpp:96:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
node_sqlite3.target.mk:109: recipe for target 'Release/obj.target/node_sqlite3/src/nodejs/Sqlite3Client.o' failed
make: *** [Release/obj.target/node_sqlite3/src/nodejs/Sqlite3Client.o] Error 1
make: Leaving directory '/var/www/blog/node_modules/node-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.32-xxxx-grs-ipv6-64
gyp ERR! command "/root/.nvm/v4.1.1/bin/node" "/root/.nvm/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/blog/node_modules/node-sqlite3
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/root/.nvm/v4.1.1/bin/node" "/root/.nvm/v4.1.1/bin/npm" "i" "node-sqlite3"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! node-sqlite3@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sqlite3@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/blog/npm-debug.log
root@ks3371007:/var/www/blog# npm i node-sqlite3^C
root@ks3371007:/var/www/blog# D^C
root@ks3371007:/var/www/blog# node-gyp rebuild
```

**Comment by emorling** [comment]
@DCKT did you find a solution?

**Comment by catalin-ciobanu** [comment]
@DCKT any news ?

**Comment by emorling** [comment]
@catalin-ciobanu @DCKT This worked for me: npm install https://github.com/mapbox/node-sqlite3/tarball/master

**Comment by joebartels** [comment]
npm installing master did the trick for me as well. thanks for sharing @emorling !

**Comment by DCKT** [comment]
Hi guys sorry for the late response but install from the master is the right solution : **it works !**
Thanks !

**Comment by marijnh** [comment]
Might be a good idea to push a new version to NPM, as the current NPM package is two years old and, apparently, broken.
