### ISSUE TITLE
Not installing on Centos with node v5

### ISSUE THREAD

**Issue by lindenle** [mapbox/node-sqlite3#537]
```
[root@4064d8f42150 extractor]# npm install sqlite3

> sqlite3@3.1.0 install /src/extractor/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/which/which.js:73:28)
gyp ERR! stack     at E (/root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/which/which.js:76:29)
gyp ERR! stack     at /root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/which/which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-49-generic
gyp ERR! command "/root/.nvm/versions/node/v5.0.0/bin/node" "/root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/src/extractor/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/src/extractor/node_modules/sqlite3/lib/binding/node-v47-linux-x64"
gyp ERR! cwd /src/extractor/node_modules/sqlite3
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v5.0.0/bin/node /root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/src/extractor/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/src/extractor/node_modules/sqlite3/lib/binding/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/src/extractor/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-49-generic
node-pre-gyp ERR! command "/root/.nvm/versions/node/v5.0.0/bin/node" "/src/extractor/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /src/extractor/node_modules/sqlite3
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok
Failed to execute '/root/.nvm/versions/node/v5.0.0/bin/node /root/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/src/extractor/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/src/extractor/node_modules/sqlite3/lib/binding/node-v47-linux-x64' (1)
npm WARN EPACKAGEJSON extractor@0.0.1 No repository field.
npm ERR! Linux 3.16.0-49-generic
npm ERR! argv "/root/.nvm/versions/node/v5.0.0/bin/node" "/root/.nvm/versions/node/v5.0.0/bin/npm" "install" "sqlite3"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/extractor/npm-debug.log
```

**Comment by Mithgol** [comment]
The `sqlite3` module does not currently support Node.js v5.x engine (that was released yesterday), and such support would probably require a transition to the current version (2.1.0) of `nan` ([Native Abstractions for Node.js](https://github.com/nodejs/nan#native-abstractions-for-nodejs)); that version was [successfully tested](https://travis-ci.org/nodejs/nan/builds/88349738) on Node.js version 5 about 6 hours ago.

**Comment by springmeyer** [comment]
v5 support is working fine (builds okay and all tests pass) as far as I can tell. So we'll provide binaries in the next release: https://github.com/mapbox/node-sqlite3/issues/539

**Comment by migueloop** [comment]
Any solution? Should I downgrade anything?
