### ISSUE TITLE
node-gyp fails to build sqlite3: /root/.node-gyp/5.0.0/common.gypi not found

### ISSUE THREAD

**Issue by yurivict** [mapbox/node-sqlite3#561]
I first run 'npm install --ignore-scripts', then 'npm rebuild'.

Here is log:
```
> sqlite3@3.1.1 install /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp: /root/.node-gyp/5.0.0/common.gypi not found (cwd: /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 10.2-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v47-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v47-freebsd-x64" "--python=/usr/local/bin/python2"
gyp ERR! cwd /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

**Comment by yurivict** [comment]
Moved issue to node-gyp
