### ISSUE TITLE
build fail for node-webkit 0.12.3 on osx

### ISSUE THREAD

**Issue by songyihong** [mapbox/node-sqlite3#582]
I want to use sqlite3 in node-webkit
I use this command `node-pre-gyp rebuild --runtime=node-webkit --target=0.12.3`
It build fail, the console print:
```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.18
node-pre-gyp info using node@0.12.9 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@0.12.9 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@0.12.9 | darwin | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.12.3/nw-headers-v0.12.3.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:561:26)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "configure" "--runtime=node-webkit" "--target=0.12.3" "--module=/Users/im/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/im/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64"
gyp ERR! cwd /Users/im/node_modules/sqlite3
gyp ERR! node -v v0.12.9
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --runtime=node-webkit --target=0.12.3 --module=/Users/im/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/im/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1016:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
node-pre-gyp ERR! System Darwin 15.2.0
node-pre-gyp ERR! command "node" "/usr/local/bin/node-pre-gyp" "rebuild" "--runtime=node-webkit" "--target=0.12.3"
node-pre-gyp ERR! cwd /Users/im/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.9
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok 
Failed to execute 'nw-gyp configure --runtime=node-webkit --target=0.12.3 --module=/Users/im/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/im/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64' (1)
```

**Comment by tmcw** [comment]
Closing in favor of #497
