### ISSUE TITLE
Error building from source on BusyBox

### ISSUE THREAD

**Issue by mrvini** [mapbox/node-sqlite3#625]
I am trying to build library from source and its failing,**please help or advice**, seems like build is choking on the stripped version of **ar**. Does anyone knows how to solve this?

**OS:** BusyBox v1.23.1 (2015-12-14 13:18:35 MST) multi-call binary.
**Node:** v4.4.2
**NPM:** 2.15.0
**node-pre-gyp:** v0.6.26

command running: ```node node_modules/.bin/node-pre-gyp rebuild```

**Error Log**
```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.26
node-pre-gyp info using node@4.4.2 | linux | arm
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.2 | linux | arm
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.2 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/sqlite3/node-sqlite3-master/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.4.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.4.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/sqlite3/node-sqlite3-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.2 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/opt/sqlite3/node-sqlite3-master/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o







  AR(target) Release/obj.target/deps/sqlite3.a
ar: invalid option -- 's'
BusyBox v1.23.1 (2015-12-14 13:18:35 MST) multi-call binary.

Usage: ar [-o] [-v] [-p] [-t] [-x] ARCHIVE FILES

make: *** [Release/obj.target/deps/sqlite3.a] Error 1
make: Leaving directory `/opt/sqlite3/node-sqlite3-master/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.0.0-ts-armv7l
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/opt/sqlite3/node-sqlite3-master/lib/binding/node-v46-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/opt/sqlite3/node-sqlite3-master/lib/binding/node-v46-linux-arm"
gyp ERR! cwd /opt/sqlite3/node-sqlite3-master
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/opt/sqlite3/node-sqlite3-master/lib/binding/node-v46-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/sqlite3/node-sqlite3-master/lib/binding/node-v46-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/sqlite3/node-sqlite3-master/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.0.0-ts-armv7l
node-pre-gyp ERR! command "/usr/bin/node" "/opt/sqlite3/node-sqlite3-master/node_modules/.bin/node-pre-gyp" "rebuild"
node-pre-gyp ERR! cwd /opt/sqlite3/node-sqlite3-master
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/opt/sqlite3/node-sqlite3-master/lib/binding/node-v46-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/sqlite3/node-sqlite3-master/lib/binding/node-v46-linux-arm' (1)

```

**Comment by mrvini** [comment]
well, after a day of trying different things, I got it working. 
I've recompiled "ar" separately and replaced BusyBox "ar" distribution with mine. After that it went fine.
I'll attache lib just in case anyone will be looking for one.
[node-v46-linux-x64.tar.gz](https://github.com/mapbox/node-sqlite3/files/211633/node-v46-linux-x64.tar.gz)
