### ISSUE TITLE
Error: Cannot find module 'nopt' on npm-installing 3.1.4 release

### ISSUE THREAD

**Issue by dbaba** [mapbox/node-sqlite3#655]
With 3.1.4, I got the following error while npm-installing:

```
# cd /tmp
# npm install sqlite3 --loglevel=info
npm info it worked if it ends with ok
npm info using npm@2.15.5
npm info using node@v4.4.5
npm info addNameTag [ 'sqlite3', 'latest' ]
npm info attempt registry request try #1 at 12:43:00 AM
npm http request GET https://registry.npmjs.org/sqlite3
npm http 304 https://registry.npmjs.org/sqlite3
npm info install sqlite3@3.1.4 into /tmp
npm info installOne sqlite3@3.1.4
npm info preinstall sqlite3@3.1.4
npm info attempt registry request try #1 at 12:43:01 AM
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm info install nan@2.3.5 into /tmp/node_modules/sqlite3
npm info installOne nan@2.3.5
npm info preinstall nan@2.3.5
npm info build /tmp/node_modules/sqlite3/node_modules/nan
npm info linkStuff nan@2.3.5
npm info install nan@2.3.5
npm info postinstall nan@2.3.5
npm info build /tmp/node_modules/sqlite3
npm info linkStuff sqlite3@3.1.4
npm info build /tmp/node_modules/sqlite3/node_modules/node-pre-gyp
npm info preinstall node-pre-gyp@0.6.28
npm info linkStuff node-pre-gyp@0.6.28
npm info install node-pre-gyp@0.6.28
npm info postinstall node-pre-gyp@0.6.28
npm info install sqlite3@3.1.4

> sqlite3@3.1.4 install /tmp/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

module.js:327
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm info sqlite3@3.1.4 Failed to exec install script
npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "sqlite3" "--loglevel=info"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm info preuninstall sqlite3@3.1.4
npm info uninstall sqlite3@3.1.4
npm info postuninstall sqlite3@3.1.4

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

However, installing 3.1.3 was successful as follows:
```
# rm -fr node_modules
# npm install sqlite3@3.1.3
/
> sqlite3@3.1.3 install /tmp/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/tmp/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
sqlite3@3.1.3 node_modules/sqlite3
└── nan@2.2.1
```

So 3.1.4 release package seems to be corrupted. Or am I missing something?

node version and OS I used:

```
# node -v
v4.4.5
# npm -v
2.15.5
# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
```

**Comment by mwittig** [comment]
@dbaba Can you please correct the title, i.e., the module not found is 'nopt'. Thanks

**Comment by mwittig** [comment]
Looks like a packaging error "I declared (the) dependency as well as bundledDependency to node-pre-gyp but before issuing npm publish I forgot to do npm install in my module local directory.". Found at <https://github.com/mapbox/node-pre-gyp/issues/67>. 

As far as I understand this, it has already bean fixed on master by commit https://github.com/mapbox/node-sqlite3/commit/9a038b503c89e83a8e45098df37764507de2b903

**Comment by dbaba** [comment]
@mwittig sure, I corrected it and thank you for the comment.

Well, I tried it again and only the EPEL version of node (v0.10.42) and npm(v1.3.6) caused the error, which are different from node v4.4.5 and npm v2.15.5 described above my initial report.

```
$ docker run -ti --rm centos:7 bash
--- on the docker container ---
# yum install -y epel-release
# yum install -y npm
# npm install sqlite3
=> failed!

# node -v; npm -v
v0.10.42
1.3.6
# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 
```
In addition, I couldn't reproduce the error with Node v4.4.5. So I will close the ticket for now and update when I get new info.

Just info: I used the following commands to try to reproduce the issue though they were all successful.
```
# rpm -Uvh https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodejs-4.4.5-1nodesource.el7.centos.x86_64.rpm
# npm install sqlite3
=> Success

# rpm -Uvh https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm
# npm install sqlite3
=> Success

# rpm -Uvh https://rpm.nodesource.com/pub_0.10/el/7/x86_64/nodejs-0.10.45-1nodesource.el7.centos.x86_64.rpm
# npm install sqlite3
=> Success

# yum install -y epel-release
# yum install -y npm
# yum install -y which
# curl https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh | bash
# source ~/.bash_profile

# nvm install v4.4.5
# npm install sqlite3
=> Success

# nvm install v0.10.45
# npm install sqlite3
=> Success

# nvm install v0.12.9
# npm install sqlite3
=> Success
```

**Comment by bioball** [comment]
I'm seeing this issue as well.

```bash
$ node --version
=> v0.10.46
$ npm --version
=> 2.15.1
$ npm install sqlite3
\
> sqlite3@3.1.4 install <PATH>/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build


module.js:340
    throw err;
          ^
Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<PATH>/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
