### ISSUE TITLE
Windows 10 install fails to find .binding file

### ISSUE THREAD

**Issue by Ralle** [mapbox/node-sqlite3#807]
module.js:340
            throw err;
                  ^
        Error: Cannot find module 'D:\Dropbox\MDCMaxWeb\node_modules\sqlite3\lib\binding\node-v11-win32-ia32\node_sqlite3.node'
            at Function.Module._resolveFilename (module.js:338:15)
            at Function.Module._load (module.js:280:25)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)
            at Object.<anonymous> (D:\Dropbox\MDCMaxWeb\node_modules\sqlite3\lib\sqlite3.js:4:15)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)

I see this folder instead:
.\node_modules\sqlite3\lib\binding\node-v48-win32-ia32\node_sqlite3.node

**Comment by Ralle** [comment]
Was using an old version of Nodejs.
