### ISSUE TITLE
Support for node8

### ISSUE THREAD

**Issue by devinivy** [mapbox/node-sqlite3#826]
When I attempted to use node8/npm5 with my application, it caught a snag trying to install this package.  I didn't necessarily expect it to work, given that the readme of this module makes it clear that support only goes through node7 today– this is just a feature request.  Let me know if I can be useful with more information or possibly with any newcomer-friendly contributions to this module.  Here's the error I got during install,
```
❯ npm install

> sqlite3@3.1.8 install /project/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/project/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/project/node_modules/node-pre-gyp/lib/install.js:165:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/project/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/project/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/project/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:503:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:466:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:458:3)
node-pre-gyp ERR! System Darwin 15.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /project/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Cannot read property 'version' of null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2017-06-01T12_54_58_721Z-debug.log
```

**Comment by devinivy** [comment]
Ohp, I just saw https://github.com/mapbox/node-sqlite3/issues/825!

I'll give this another shot, and report back if I can get it to work.

**Comment by devinivy** [comment]
I don't know what caused this originally, but all seems to be OK :) Might be worth tweaking the readme if node8 is officially supported?

**Comment by springmeyer** [comment]
> TypeError: Cannot read property 'version' of null

Turns out this is happening due to a behavior change in npm5: https://github.com/npm/npm/issues/16926. I recommend working around this by sticking to node v6 for now - refs https://github.com/mapbox/node-pre-gyp/issues/298#issuecomment-305859412

**Comment by devinivy** [comment]
Ah, that makes sense.  Thanks for taking a peek.
