### ISSUE TITLE
Empty table - cannot read property of undefined

### ISSUE THREAD

**Issue by davidmckenzie** [mapbox/node-sqlite3#832]
Getting a TypeError when attempting to run the following query on an empty table:

```
    db.serialize(() => {
        db.get("SELECT id FROM messages ORDER BY id DESC LIMIT 1", [], function(err, row) {
            if (err) {
                console.log(err);
                db.close((e) => {
                    if (e) console.log(e);
                });                 
            } else {
                // do some other stuff
            }
        });
    });
```

Error:

```
/home/ubuntu/workspace/server/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'id' of undefined
    at Statement.<anonymous> (/home/ubuntu/workspace/server/routes/api.js:133:49)
--> in Database#get('SELECT id FROM messages ORDER BY id DESC LIMIT 1', [], [Function])
    at Database.<anonymous> (/home/ubuntu/workspace/server/routes/api.js:126:12)
    at /home/ubuntu/workspace/server/routes/api.js:125:8
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/workspace/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/workspace/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/workspace/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/workspace/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/workspace/server/node_modules/express/lib/router/index.js:275:10)
```

Running the command in sqlite manually returns an empty result, as expected:

```
sqlite> SELECT id FROM messages ORDER BY id DESC LIMIT 1;
sqlite> 
```

Is this expected behaviour? If so, what's the recommended solution - do I insert a dummy row after my 'CREATE TABLE IF NOT EXISTS'? Or do I wrap the query in a if/else on COUNT(*) = 0?

**Comment by davidmckenzie** [comment]
Erm, never mind, easy fix. Just needed an if/else on "row" in the callback.
