### ISSUE TITLE
module not found even if it has been installed

### ISSUE THREAD

**Issue by aprilmintacpineda** [mapbox/node-sqlite3#838]
Hi everyone, I am trying to create a desktop app with electron, when I run with electron, on the console there is this error

```
module.js:472 Uncaught Error: Cannot find module 'C:\Users\aprilpineda\Documents\projects\desktop\experiments\2-sample\node_modules\sqlite3\lib\binding\electron-v1.6-win32-x64\node_sqlite3.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\aprilpineda\Documents\projects\desktop\experiments\2-sample\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\2-sample\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Object.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\2-sample\node_modules\sqlite3\lib\sqlite3.js:190:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

here is my package json
```
"dependencies": {
    "path": "^0.12.7",
    "sequelize": "^4.2.0",
    "sqlite3": "^3.1.8",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "electron": "^1.6.11",
    "electron-packager": "^8.7.2",
    "electron-packager-interactive": "^0.1.2"
  }
```

`main.js`
```
'use strict';

const electron = require('electron');
const path = require('path');
const url = require('url');

const Browser = electron.BrowserWindow;
const app = electron.app;

let mainScreen;
let splashScreen;

function createSplashScreen() {
  splashScreen = new Browser({
    minWidth: 400,
    minHeight: 200,
    maxWidth: 400,
    maxHeight: 200,
    width: 400,
    height: 200,
    frame: false
  });

  splashScreen.loadURL(url.format({
    pathname: path.join(__dirname, 'screens/splash.html'),
    protocol: 'file',
    slashes: true
  }));
}

function createMainScreen() {
  mainScreen = new Browser({
    minWidth: 1024,
    minHeight: 600,
    width: 1024,
    height: 600,
    show: false
  });

  mainScreen.loadURL(url.format({
    pathname: path.join(__dirname, 'screens/main.html'),
    protocol: 'file',
    slashes: true
  }));
}

app.on('ready', () => {
  createMainScreen();
  createSplashScreen();

  mainScreen.once('ready-to-show', () => {
    mainScreen.show();
    splashScreen.close();
  });
});

app.on('window-all-closed', () => {
  app.quit();
});
```

and `main.html`

```
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <a id="get">Get</a>

  <script type="text/javascript">
    const path = require('path');
    const sqlite3 = require('sqlite3');
    const Sequelize = require('sequelize');

    document.querySelector('#get').addEventListener('click', function() {
      let sequelize = new Sequelize({
        dialect: 'sqlite',
        storage: path.join(__dirname, '../database/main.sqlite')
      });

      sequelize.authenticate()
        .then(function() {
          console.log('connected');
        })
        .catch(function(error) {
          console.log(error);
        });
    }, false);
  </script>
</body>
</html>
````

here is the repo that you can use to replicate or check the error
https://github.com/four-eyes-04-04/test

**Comment by four-eyes-04-04** [comment]
I upgraded to node 8.1.2 and tried to install sqlite3 again, I was given the following output (which I can't even understand):

```
npm install --save sqlite3

> sqlite3@3.1.8 install C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\experiments\\1-testproject\\node_modules\
\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@8.1.2 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modu
les\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v57-win32-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v57-win32-x64.tar.gz
node-pre-gyp info install unpacking node_sqlite3.node
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v57-win3
2-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@8.1.2 (node-v57 ABI) (falling back to source c
ompile with node-gyp)
node-pre-gyp http read ECONNRESET
node-pre-gyp verb command build [ 'rebuild' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\bui
  ld\Release\\sqlite3.lib
  database.cc
  node_sqlite3.cc
  statement.cc
  win_delay_load_hook.cc
..\src\database.cc(133): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\aprilpineda\Documents
\projects\desktop\experiments\1-testproject\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  c:\users\aprilpineda\.node-gyp\8.1.2\include\node\v8.h(2951): note: see declaration of 'v8::Object::ForceSet'
..\src\statement.cc(103): warning C4996: 'v8::Object::ForceSet': was declared deprecated..\src\database.cc(134): warnin
g C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\aprilpineda\Documents\projects\desktop\experiments\1
-testproject\node_modules\sqlite3\build\node_sqlite3.vcxproj]

  c:\users\aprilpineda\.node-gyp\8.1.2\include\node\v8.h(2951): note: see declaration of 'v8::Object::ForceSet'
  c:\users\aprilpineda\.node-gyp\8.1.2\include\node\v8.h(2951): note: see declaration of 'v8::Object::ForceSet'
..\src\statement.cc(277): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\User
s\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\build\node_sqlite3.vcxproj]
c:\users\aprilpineda\documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\node_modules\nan\nan_new
.h(208): warning C4244: 'argument': conversion from 'sqlite3_int64' to 'double', possible loss of data (compiling sourc
e file ..\src\statement.cc) [C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sql
ite3\build\node_sqlite3.vcxproj]
  ..\src\statement.cc(479): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::
  Number,sqlite3_int64>(A0)' being compiled
          with
          [
              A0=sqlite3_int64
          ]
c:\users\aprilpineda\documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\node_modules\nan\nan_new
.h(208): warning C4244: 'argument': conversion from 'sqlite3_int64' to 'double', possible loss of data (compiling sourc
e file ..\src\database.cc) [C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqli
te3\build\node_sqlite3.vcxproj]
  ..\src\database.cc(502): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::N
  umber,sqlite3_int64>(A0)' being compiled
          with
          [
              A0=sqlite3_int64
          ]
C:\Users\aprilpineda\.node-gyp\8.1.2\x64\node.lib : fatal error LNK1127: library is corrupt [C:\Users\aprilpineda\Docum
ents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\nod
e_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\experiment
s\\1-testproject\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\aprilpine
da\\Documents\\projects\\desktop\\experiments\\1-testproject\\node_modules\\sqlite3\\lib\\binding\\node-v57-win32-x64\\n
ode_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\expe
riments\\1-testproject\\node_modules\\sqlite3\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\aprilpineda\Documents\projec
ts\desktop\experiments\1-testproject\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\a
prilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node
_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-tes
tproject\node_modules\sqlite3\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-t
estproject\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aprilpineda\\Documents\\projects\\desktop\\e
xperiments\\1-testproject\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-t
o-build"
node-pre-gyp ERR! cwd C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testpr
oject\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\aprilpineda\Documents\projects\d
esktop\experiments\1-testproject\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=nod
e_sqlite3 --module_path=C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-testproject\node_modules\sqlite3\l
ib\binding\node-v57-win32-x64' (1)
npm WARN 1-testproject@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aprilpineda\AppData\Roaming\npm-cache\_logs\2017-06-27T15_10_12_645Z-debug.log
```

**Comment by rohmanhm** [comment]
I hope this will helps you

https://github.com/typeorm/typeorm/issues/2456#issuecomment-402359745

**Comment by aprilmintacpineda** [comment]
aa, this was a year ago, yeah I managed to solve this, I can't remember how though.
