### ISSUE TITLE
Bug won't compile for projects with '(' or ')' in path.

### ISSUE THREAD

**Issue by p0indexter** [mapbox/node-sqlite3#871]
So after banging my head against the wall for a few hours trying to figure out the meaning of life or more specifically why sqlite3 wouldn't compile for my electron app. Eventually, I discovered that the problem was the '(' and ')' in my Dropbox folder name. I moved the project to a path without parenthesis and it compiled flawlessly. It took me a while to find this bug because level down was compiling properly. Check for bugs in your make file and compile scripts. I suspect the path isn't being wraped in doubble quotes or something of that nature.

```> sqlite3@3.1.9 install /Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.9/electron-v1.7-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.9 and electron@1.7.5 (electron-v1.7 ABI) (falling back to source compile with node-gyp) 
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `LD_LIBRARY_PATH=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/build/Release/lib.host:/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/build/Release/obj/gen/sqlite-autoconf-3150000; python ./extract.py ./sqlite-autoconf-3150000.tar.gz "/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/build/Release/obj/gen"'
make: *** [Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 2
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node@6/6.11.2/bin/node" "/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64"
gyp ERR! cwd /Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node@6/6.11.2/bin/node /Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node@6/6.11.2/bin/node" "/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node@6/6.11.2/bin/node /Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/calebsmith/Dropbox (Emi Imaging)/Programing/Electron/EMI/FTN/cacfp/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64' (1)
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.1.0 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.1.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/calebsmith/.npm/_logs/2017-09-05T18_10_06_988Z-debug.log```

**Comment by springmeyer** [comment]
For now you will need to remove the spaces and `(` - these are not supported. The problem is not in node-sqlite3 it is in node-gyp: https://github.com/nodejs/node-gyp/issues/65
