### ISSUE TITLE
Build problem for nw.js

### ISSUE THREAD

**Issue by GitDaimos** [mapbox/node-sqlite3#886]
Im trying to build node-sqlite3 with:
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.25.2

and i have error:
 ```
C:\Users\username\.nw-gyp\0.25.2\deps\v8\include\v8.h(3102): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\node_sqlite3.cc)
..\src\statement.cc(103): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot c
onvert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [D:\vhosts\_temp\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  ..\src\statement.cc(103): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\statement.cc(277): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\vhosts\_temp\mdb\node_modules\sqlite3\build\node_sqlit
e3.vcxproj]
..\src\database.cc(133): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot co
nvert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [D:\vhosts\_temp\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  ..\src\database.cc(133): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\database.cc(134): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot co
nvert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [D:\vhosts\_temp\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  ..\src\database.cc(134): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--fallback-to-build" "--module=D:\\vhosts\\_temp\\mdb\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.25.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\\vhosts\\_temp\\mdb\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.25.2-win32-x64"
gyp ERR! cwd D:\vhosts\_temp\mdb\node_modules\sqlite3
gyp ERR! node -v v6.9.1
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd build --fallback-to-build --module=D:\vhosts\_temp\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\vhosts\_temp\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\vhosts\_temp\mdb\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\vhosts\\_temp\\mdb\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\vhosts\_temp\mdb\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd build --fallback-to-build --module=D:\vhosts\_temp\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\vhosts\_temp\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64' (1)
npm WARN helloworld@ No description
npm WARN helloworld@ No repository field.
npm WARN helloworld@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2017-09-22T11_25_18_287Z-debug.log
```
last lines from debug.log:

```
2502 verbose lifecycle sqlite3@3.1.11~install: CWD: D:\vhosts\_temp\mdb\node_modules\sqlite3
2503 silly lifecycle sqlite3@3.1.11~install: Args: [ '/d /s /c', 'node-pre-gyp install --fallback-to-build' ]
2504 silly lifecycle sqlite3@3.1.11~install: Returned: code: 1  signal: null
2505 info lifecycle sqlite3@3.1.11~install: Failed to exec install script
2506 verbose unlock done using C:\Users\username\AppData\Roaming\npm-cache\_locks\staging-d240436da8527e75.lock for D:\vhosts\_temp\mdb\node_modules\.staging
2507 warn helloworld@ No description
2508 warn helloworld@ No repository field.
2509 warn helloworld@ No license field.
2510 verbose stack Error: sqlite3@3.1.11 install: `node-pre-gyp install --fallback-to-build`
2510 verbose stack Exit status 1
2510 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
2510 verbose stack     at emitTwo (events.js:106:13)
2510 verbose stack     at EventEmitter.emit (events.js:191:7)
2510 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2510 verbose stack     at emitTwo (events.js:106:13)
2510 verbose stack     at ChildProcess.emit (events.js:191:7)
2510 verbose stack     at maybeClose (internal/child_process.js:877:16)
2510 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2511 verbose pkgid sqlite3@3.1.11
2512 verbose cwd D:\vhosts\_temp\mdb
2513 verbose Windows_NT 10.0.15063
2514 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.25.2"
2515 verbose node v6.9.1
2516 verbose npm  v5.4.2
2517 error code ELIFECYCLE
2518 error errno 1
2519 error sqlite3@3.1.11 install: `node-pre-gyp install --fallback-to-build`
2519 error Exit status 1
2520 error Failed at the sqlite3@3.1.11 install script.
2520 error This is probably not a problem with npm. There is likely additional logging output above.
2521 verbose exit [ 1, true ]
```

**Comment by springmeyer** [comment]
This is fixed in https://github.com/mapbox/node-sqlite3/commit/e3f50025942039af9a010ae19d639d3541908422 and should no longer be a problem in the upcoming release: `sqlite3@3.1.12`

**Comment by GitDaimos** [comment]
This was a fast reaction ;) Thanks, but i see there are more problems. On other comupter, windows 10 i have:

`ImportError: cannot import name _remove_dead_weakref
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [E:\nwjs\mdb\n
ode_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Daimos\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\nodejs\\node.exe" "C:\\Users\\Daimos\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--fallback-to-build" "--module=E:\\nwjs\\mdb\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.25.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\nwjs\\mdb\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.25.2-win32-x64"
gyp ERR! cwd E:\nwjs\mdb\node_modules\sqlite3
gyp ERR! node -v v6.9.1
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd build --fallback-to-build --module=E:\nwjs\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\nwjs\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\nwjs\mdb\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nwjs\\mdb\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\nwjs\mdb\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp ERR! not ok`

**Comment by springmeyer** [comment]
`sqlite3@3.1.12` is released. Please try again and re-open a new issue if the problem persists.
