### ISSUE TITLE
Build problem for nw.js

### ISSUE THREAD

**Issue by GitDaimos** [mapbox/node-sqlite3#888]
Im trying now again to build node-sqlite3 with:
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.25.2

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  Traceback (most recent call last):
    File "..\..\deps\extract.py", line 2, in <module>
      import tarfile
    File "C:\Python27\lib\tarfile.py", line 52, in <module>
      import copy
    File "C:\Python27\lib\copy.py", line 52, in <module>
      import weakref
    File "C:\Python27\lib\weakref.py", line 14, in <module>
      from _weakref import (
  ImportError: cannot import name _remove_dead_weakref
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [E:\nwjs\mdb\n
ode_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Daimos\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\nodejs\\node.exe" "C:\\Users\\Daimos\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--fallback-to-build" "--module=E:\\nwjs\\mdb\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.25.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\nwjs\\mdb\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.25.2-win32-x64"
gyp ERR! cwd E:\nwjs\mdb\node_modules\sqlite3
gyp ERR! node -v v6.9.1
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd build --fallback-to-build --module=E:\nwjs\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\nwjs\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\nwjs\mdb\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nwjs\\mdb\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\nwjs\mdb\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd build --fallback-to-build --module=E:\nwjs\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\nwjs\mdb\node_modules\sqlite3\lib\binding\node-webkit-v0.25.2-win32-x64' (1)
npm WARN Error: EPERM: operation not permitted, scandir 'E:\nwjs\mdb\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'E:\nwjs\mdb\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules'
npm WARN     at Error (native)
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'E:\\nwjs\\mdb\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\tar-pack\\node_modules\\fstream-ignore\\node_modules\\minimatch\\node_modules\'\n    at Error (native)',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'E:\\nwjs\\mdb\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\tar-pack\\node_modules\\fstream-ignore\\node_modules\\minimatch\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daimos\AppData\Roaming\npm-cache\_logs\2017-09-22T16_30_05_058Z-debug.log
```

**Comment by GitDaimos** [comment]
updated node js to v6.11.3 and still same problem.

**Comment by springmeyer** [comment]
Looks like several new problems:

> ImportError: cannot import name _remove_dead_weakref

Is a python error. What version of python do you have installed? You need 2.x not 3.x

**Comment by GitDaimos** [comment]
Its 2.7.14 says readme.txt inside C:\Python27 and I see gyp use it. But I installed before:
npm install --global --production windows-build-tools
and when i check:
python --version
its 2.7.11 so windows-build-tools could change my installation i think. But its still 2.x version

**Comment by GitDaimos** [comment]
Ok its works. I installed fresh Python 2.7.14 x64.
Problem was with windows-build-tools. During installation, there was Python 2.7 32bits installed.
Everything works fine now, thanks for help. But many yellows lines if you interested:

```
 win_delay_load_hook.cc
e:\nwjs\mdb\node_modules\nan\nan_maybe_43_inl.h(112): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\sta
tement.cc) [E:\nwjs\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  C:\Users\Daimos\.nw-gyp\0.25.2\deps\v8\include\v8.h(3102): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\statement.c
  c)
e:\nwjs\mdb\node_modules\nan\nan_maybe_43_inl.h(112): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\dat
abase.cc) [E:\nwjs\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  C:\Users\Daimos\.nw-gyp\0.25.2\deps\v8\include\v8.h(3102): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\database.cc
  )
e:\nwjs\mdb\node_modules\nan\nan_maybe_43_inl.h(112): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\nod
e_sqlite3.cc) [E:\nwjs\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  C:\Users\Daimos\.nw-gyp\0.25.2\deps\v8\include\v8.h(3102): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\node_sqlite
  3.cc)
..\src\statement.cc(277): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [E:\nwjs\mdb\node_modules\sqlite3\build
\node_sqlite3.vcxproj]
e:\nwjs\mdb\node_modules\nan\nan_new.h(208): warning C4244: 'argument': conversion from 'sqlite3_int64' to 'double', possible loss of data (compiling
source file ..\src\statement.cc) [E:\nwjs\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  ..\src\statement.cc(479): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,sqlite3_int64>(A0)' bein
  g compiled
          with
          [
              A0=sqlite3_int64
          ]
e:\nwjs\mdb\node_modules\nan\nan_new.h(208): warning C4244: 'argument': conversion from 'sqlite3_int64' to 'double', possible loss of data (compiling
source file ..\src\database.cc) [E:\nwjs\mdb\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  ..\src\database.cc(502): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,sqlite3_int64>(A0)' being
   compiled
          with
          [
              A0=sqlite3_int64
          ]
     Creating library E:\nwjs\mdb\node_modules\sqlite3\build\Release\node_sqlite3.lib and object E:\nwjs\mdb\node_modules\sqlite3\build\Release\node_s
  qlite3.exp
```

**Comment by springmeyer** [comment]
Glad you got it working. Thanks for posting the warnings. One of them needs dealt with, so I've ticketed in #889. Closing now since you've resolved the core issue.
