### ISSUE TITLE
Azure Function - NodeJs - Sqlite - mscorlib - Error: A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by tayfourius** [mapbox/node-sqlite3#894]
I have nodejs azure function that using sqlite3 lib. after running the function. i got this error.

    2017-10-12T10:49:16.036 Function started
    2017-10-12T10:49:19.434 Exception while executing function: Functions.sqlite. 
    mscorlib: One or more errors occurred. Error: A dynamic link library (DLL) initialization routine failed.
     \\?\D:\home\site\wwwroot\sqlite\node_modules\sqlite3\lib\binding\node-v48-win32-
     ia32\node_sqlite3.node
     at Error (native)
     at Object.Module._extensions..node (module.js:597:18)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (D:\home\site\wwwroot\sqlite\node_modules\sqlite3\lib\sqlite3.js:4:15)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10).
     2017-10-12T10:49:19.449 Function completed (Failure, Duration=3415ms)

My function is:

    var sqlite3 = require('sqlite3').verbose();
    var db = new sqlite3.Database('./database.sqlite3');
 
    db.serialize(function() {
      db.run("CREATE TABLE lorem (info TEXT)");
 
      var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
      for (var i = 0; i < 10; i++) {
          stmt.run("Ipsum " + i);
     }
      stmt.finalize();
 
      db.each("SELECT rowid AS id, info FROM lorem", function(err, row) {
          console.log(row.id + ": " + row.info);
      });
    });
 
    db.close();

node -v 6.11.2
npm -v 3.10.10
Platform 32-bit

if I tried to run the function using kudu cmd, the function run without any problems...
     D:\home\site\wwwroot\sqlite>node index.js
any idea how to solve this error?

**Comment by Bilall-RH** [comment]
if you find a solution **please** help me

**Comment by tayfourius** [comment]
I solve the problem using Sql.js lib https://github.com/kripken/sql.js/
