### ISSUE TITLE
sqlite3 node for arm board

### ISSUE THREAD

**Issue by maits2017** [mapbox/node-sqlite3#927]
Hi,
I have to install node sqlite3 on an embedded Linux Board Device.
This Device has pre installed node version 0.12.7 and sqlite3 DB, however It does not have Internet, npm, node-gyp, nvm or node-pre-gyp.
So I have to compile node_sqlite3.node on Ubuntu development box and then copy on Devie to run my application.

I tried cross compiling with arguments --arch=arm but built binary could not run application when copied on board.
I have tried many alternatives, but nothing is working on Board.

At last I booted the same Device with Ubuntu Linux Image which had Internet access so I installed node version 0.12.7 on device and did npm to install sqlite3 which created sqlite3 bindinds for arm architecture. My assumption was that this would create the node sqlite bindings required by architecture, however Sad part is, when I copied this sqlite3 folder in previous image which does not have internet, and written a simple node PRogram to require(sqlite3), it gives Internal Error. 

```
~$ node app.js                                                                                                                                                                                    
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /home/root/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node: internal error
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/root/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Is there any work around to build sqlite3 module corresponding to my Device architecture and bypass the require(sqlite3) error.

**Comment by maits2017** [comment]
After so much of struggle I figured out a solution for this...
I generated Tool Chain for my Board Image on my dev machine
and then set the SDK Environment 
and then following command from the same shell of environment

` npm install sqlite3 --target_arch=arm --target_platform=linux --target=0.12.7`

Now here is a catch which I had to fix for building it successfully

Actually npm uses python for using node-gyp and node-pre-gyp internally but since my SDK environment also had python so npm was using my SDK python, which was giving so many issues, so as a work around, I moved all Python lib and binary from SDK path to temp location and set my PYTHONHOME of my native python environment. And that build node-sqlite3.node for my arm architecture successfully.
