### ISSUE TITLE
 npm install sqlite3@3.1.4  failed ,  who can help me??

### ISSUE THREAD

**Issue by Jackzhangpan** [mapbox/node-sqlite3#928]
```
> sqlite3@3.1.4 install E:\Gekko\gekko\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp)

E:\Gekko\gekko\node_modules\sqlite3>if not defined npm_config_node_gyp (node "E:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

E:\Gekko\gekko\node_modules\sqlite3>if not defined npm_config_node_gyp (node "E:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64 --msvs_version=2015 )  else (node "" configure --fallback-to-build --module=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64 --msvs_version=2015 )

E:\Gekko\gekko\node_modules\sqlite3>if not defined npm_config_node_gyp (node "E:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64 )  else (node "" build --fallback-to-build --module=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64 )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
E:\Gekko\gekko\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: 未找到导入的项目“E:\Microsoft.
Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\Gekko\\gekko\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\Gekko\\gekko\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd E:\Gekko\gekko\node_modules\sqlite3
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Gekko\gekko\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "E:\\nodejs\\node.exe" "E:\\Gekko\\gekko\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\Gekko\gekko\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Gekko\gekko\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3@3.1.4"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Gekko\gekko\npm-debug.log
```

**Comment by springmeyer** [comment]
Please upgrade to the latest node-sqlite3 release, which will work with node v6. It is node-sqlite3 `v3.1.13`
