### ISSUE TITLE
install sqlite3 error with electron

### ISSUE THREAD

**Issue by Mydly** [mapbox/node-sqlite3#938]
Execute the following command on my Mac.
sudo npm install sqlite3@3.1.8 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=1.7.6 --dist-url=https://atom.io/download/electron

sudo npm install sqlite3@3.1.8 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=1.7.6 --dist-url=https://atom.io/download/electron
Password:

> fsevents@1.1.3 install /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/fsevents
> node install

gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/fsevents
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/fsevents
node-pre-gyp ERR! node -v v6.11.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> node-sass@4.7.2 install /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/node-sass/vendor/darwin-x64-48 : { Error: EACCES: permission denied, mkdir '/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at sync (/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/node-sass/vendor' }

> sqlite3@3.1.8 install /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@6.11.4 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info build requesting source compile
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64 --dist-url=https://atom.io/download/electron' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.11.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/yumingliang/Documents/project/dev/Electron-React/burshOrder/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64 --dist-url=https://atom.io/download/electron' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yumingliang/.npm/_logs/2018-01-29T07_19_30_303Z-debug.log

**Comment by wmertens** [comment]
You should never use `sudo` to build `npm` packages. There is also the error `Error: EACCES: permission denied, rmdir 'build'` which is very odd since you are running as root.

It seems to me that your system could use a thorough re-install.

**Comment by Mydly** [comment]
@wmertens  If I do not use sudo to run, there will be a permission error

**Comment by wmertens** [comment]
My point exactly - never should you have to use sudo to run npm, so
there is a permissions issue on your system.

**Comment by andreistreltsov** [comment]
Might be unrelated, but I used to have all kinds of errors with Electron, SQLite and other binary packages  until I started using yarn instead of npm.

**Comment by Mydly** [comment]
Thank you for your attention。@wmertens Could you tell me how to solve this permission issue on your system?

**Comment by Mydly** [comment]
I also have such a similar experience。yarn is better than npm.

**Comment by ChaoYuLeo** [comment]
You can try to use 
`npm config set unsafe-perm true`
