### ISSUE TITLE
Rebuild for electron 1.8.3 problem on Windows 7

### ISSUE THREAD

**Issue by ncortines** [mapbox/node-sqlite3#953]
Hi,

I'm currently using `electron-builder` to rebuild the bindings for electron 1.7.6 on Windows 7 and Windows 10 machines (64 bits), and I have no issue with that.

Now I need to upgrade electron to version 1.8.3, and I have no problems on the Windows 10 machine, but on the Windows 7 machine I'm getting the following console output:

```
13:43:43 Warning: Please use as subcommand: electron-builder install-app-deps
13:43:43 electron-builder 19.4.0
13:43:43 Installing app dependencies for arch x64 to C:\jenkins\workspace\DesktopApp\Review\app
13:44:03 Error: c:\Program Files\nodejs\node.exe exited with code 1
13:44:03 Output:
13:44:03 
13:44:03 > sqlite3@3.1.13 install C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3
13:44:03 > node-pre-gyp install --fallback-to-build
13:44:03 
13:44:03 Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
13:44:03   unpack_sqlite_dep
13:44:03   sqlite3.c
13:44:03   win_delay_load_hook.cc
13:44:03   sqlite3.vcxproj -> C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\Release\\sqlite3.lib
13:44:03   database.cc
13:44:03   node_sqlite3.cc
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4028): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4031): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4028): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4104): error C2610: 'v8::WasmModuleObjectBuilder::WasmModuleObjectBuilder(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4031): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4106): error C2610: 'v8::WasmModuleObjectBuilder &v8::WasmModuleObjectBuilder::operator =(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4104): error C2610: 'v8::WasmModuleObjectBuilder::WasmModuleObjectBuilder(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4106): error C2610: 'v8::WasmModuleObjectBuilder &v8::WasmModuleObjectBuilder::operator =(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03   statement.cc
13:44:03   win_delay_load_hook.cc
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4028): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4031): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4104): error C2610: 'v8::WasmModuleObjectBuilder::WasmModuleObjectBuilder(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 C:\Users\jenkins\.electron-gyp\iojs-1.8.3\deps\v8\include\v8.h(4106): error C2610: 'v8::WasmModuleObjectBuilder &v8::WasmModuleObjectBuilder::operator =(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 ..\src\statement.cc(277): warning C4244: 'argument' : conversion from 'int64_t' to 'int', possible loss of data [C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\build\node_sqlite3.vcxproj]
13:44:03 Failed to execute 'c:\Program Files\nodejs\node.exe C:\Users\jenkins\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)
13:44:03 
13:44:03 Error output:
13:44:03 gyp ERR! build error 
13:44:03 gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
13:44:03 gyp ERR! stack     at ChildProcess.onExit (C:\Users\jenkins\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
13:44:03 gyp ERR! stack     at emitTwo (events.js:126:13)
13:44:03 gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
13:44:03 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
13:44:03 gyp ERR! System Windows_NT 6.2.9200
13:44:03 gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jenkins\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\jenkins\\workspace\\DesktopApp\\Review\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\jenkins\\workspace\\DesktopApp\\Review\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64"
13:44:03 gyp ERR! cwd C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3
13:44:03 gyp ERR! node -v v8.10.0
13:44:03 gyp ERR! node-gyp -v v3.6.2
13:44:03 gyp ERR! not ok 
13:44:03 node-pre-gyp ERR! build error 
13:44:03 node-pre-gyp ERR! stack Error: Failed to execute 'c:\Program Files\nodejs\node.exe C:\Users\jenkins\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)
13:44:03 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
13:44:03 node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
13:44:03 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
13:44:03 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
13:44:03 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13:44:03 node-pre-gyp ERR! System Windows_NT 6.2.9200
13:44:03 node-pre-gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "C:\\jenkins\\workspace\\DesktopApp\\Review\\app\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
13:44:03 node-pre-gyp ERR! cwd C:\jenkins\workspace\DesktopApp\Review\app\node_modules\sqlite3
13:44:03 node-pre-gyp ERR! node -v v8.10.0
13:44:03 node-pre-gyp ERR! node-pre-gyp -v v0.6.38
13:44:03 node-pre-gyp ERR! not ok 
13:44:03 npm WARN electron-client@7.31.0-snapshot No repository field.
13:44:03 npm WARN electron-client@7.31.0-snapshot No license field.
13:44:03 
13:44:03 npm ERR! code ELIFECYCLE
13:44:03 npm ERR! errno 1
13:44:03 npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
13:44:03 npm ERR! Exit status 1
13:44:03 npm ERR! 
13:44:03 npm ERR! Failed at the sqlite3@3.1.13 install script.
13:44:03 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13:44:03 
13:44:03 npm ERR! A complete log of this run can be found in:
13:44:03 npm ERR!     C:\Users\jenkins\AppData\Roaming\npm-cache\_logs\2018-03-14T12_44_55_919Z-debug.log
13:44:03 
13:44:03     at ChildProcess.childProcess.once.code (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder-util\src\util.ts:135:14)
13:44:03     at Object.onceWrapper (events.js:317:30)
13:44:03     at emitTwo (events.js:126:13)
13:44:03     at ChildProcess.emit (events.js:214:7)
13:44:03     at maybeClose (internal/child_process.js:925:16)
13:44:03     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13:44:03 From previous event:
13:44:03     at spawn (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder-util\src\util.ts:103:3)
13:44:03     at installDependencies (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\src\util\yarn.ts:77:3)
13:44:03     at C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\src\util\yarn.ts:14:11
13:44:03     at Generator.next (<anonymous>)
13:44:03 From previous event:
13:44:03     at installOrRebuild (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\out\util\yarn.js:34:21)
13:44:03     at C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\src\cli\install-app-deps.ts:52:2
13:44:03     at Generator.next (<anonymous>)
13:44:03     at runCallback (timers.js:794:20)
13:44:03     at tryOnImmediate (timers.js:752:5)
13:44:03 From previous event:
13:44:03     at installAppDeps (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\out\cli\install-app-deps.js:43:21)
13:44:03     at main (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\out\cli\install-app-deps.js:102:12)
13:44:03     at Object.<anonymous> (C:\jenkins\workspace\DesktopApp\Review\node_modules\electron-builder\out\cli\install-app-deps.js:106:5)
13:44:03     at Module._compile (module.js:652:30)
13:44:03     at Object.Module._extensions..js (module.js:663:10)
13:44:03     at Module.load (module.js:565:32)
13:44:03     at tryModuleLoad (module.js:505:12)
13:44:03     at Function.Module._load (module.js:497:3)
13:44:03     at Function.Module.runMain (module.js:693:10)
13:44:03     at startup (bootstrap_node.js:188:16)
13:44:03     at bootstrap_node.js:609:3
13:44:03 npm ERR! code ELIFECYCLE
13:44:03 npm ERR! errno 4294967295
13:44:03 npm ERR! electron-client@7.31.1-snapshot postinstall: `install-app-deps && gulp update-sqlite3`
13:44:03 npm ERR! Exit status 4294967295
13:44:03 npm ERR! 
13:44:03 npm ERR! Failed at the electron-client@7.31.1-snapshot postinstall script.
13:44:03 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13:44:03 
```

Any help would be greatly appreciated.

Thanks,

Juan

**Comment by ncortines** [comment]
It's most likely a problem with my build chain tools, so I'll stick with the Windows 10 machine.

**Comment by evecalm** [comment]
I have the same exact problem :(
