### ISSUE TITLE
"Failed at the sqlite3@3.1.13 install script 'node-pre-gyp install --fallback-to-build'" on Windows

### ISSUE THREAD

**Issue by mathiasfoster** [mapbox/node-sqlite3#972]
Hello all,

Windows 10, Node version 6.9.4, NPM version 3.10.10.
I'm trying to install [Gekko](https://gekko.wizb.it/docs/installation/installing_gekko_on_windows.html) and I get the following error:
```
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@6.9.4 (node-v48 ABI) (falling back to source compile with node-gyp)

C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node" --module_name=node_sqlite3 "--module_path=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64" )  else (node "" configure --fallback-to-build "--module=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node" --module_name=node_sqlite3 "--module_path=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64" )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\SOBER CHECK\\Downloads\\gekko-develop\\gekko-develop\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\SOBER CHECK\\Downloads\\gekko-develop\\gekko-develop\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SOBER CHECK\\Downloads\\gekko-develop\\gekko-develop\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SOBER CHECK\Downloads\gekko-develop\gekko-develop\npm-debug.log
```

Please help!

**Comment by avishai-ish-shalom** [comment]
Same on linux

**Comment by maksze** [comment]
I have this problem to. Linux 4.9.94-1-MANJARO, node 9.11.1

**Comment by jlguenego** [comment]
Cannot use sqlite with node because of this.

**Comment by ericblade** [comment]
am getting same here.  not sure what the previous version i had was, i went to do a commit, and it said i couldn't run tests because sqlite was missing, i ran a npm install, and it says it can't build :-S

**Comment by Bugari** [comment]
Experiencing same thing, rollback to node 9.11.1 worked.

**Comment by OmerFlame** [comment]
I think that there is a compatibility issue with sqlite3 in cooperation with Node 10.0.0. I really think going with the LTS might solve your problem, since I'm doing it now. Just a speculation. Please, I'm not a professional! For those who understand the inner workings of NPM better than me, please reply to say if I'm right.

**Comment by phiphou** [comment]
Same issue for me, doesn't install with node 10.

**Comment by springmeyer** [comment]
The v4.0.1 release supports node v9/10 now: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401

**Comment by acandael** [comment]
thx @ericblade after searching two days for a fix, rolling back to node v9.11.1 fixed it for me.

**Comment by answerquest** [comment]
Hi, rolling back to rolling back to node v9.11.1 didn't work for me.. after that trying this worked:
https://github.com/jansmolders86/mediacenterjs/issues/191#issuecomment-317437604

```
npm config set user 0
npm config set unsafe-perm true
```
I've tried soo many things by now that I have no clue about whether it was just this that did it or a combination with other things, but check out the issue linked, lot of fine details have been shared and few other ways also.

**Comment by Larryster** [comment]
node v9.11.1 worked for me and reinstalling npm...several hours later im back on track

**Comment by g8up** [comment]
In the README.md Node.js v9.x is not support ?
> The sqlite3 module works with Node.js v4.x, v6.x, v8.x, v10.x, v11.x and v12.x.

**Comment by aronreisx** [comment]
@mathiasfoster I had same issue when trying install sqlite3 on Win10.

Follow the steps:

1. Install [Windows Build Tools](https://www.npmjs.com/package/windows-build-tools) globally

- [ ] `npm i --global --production windows-build-tools`

2. Install [Node Gyp](https://www.npmjs.com/package/node-gyp)

- [ ] `npm i -g node-gyp`

3. Clear NPM Cache

- [ ] `npm cache clean`

4. Try to install Gekko again

- [ ] `npm i gekko`

**Comment by aronreisx** [comment]
> Hello, got the same problem with node 12.17
> 'Pre-built binaries not found for sqlite3@3.1.13 and node@12.17'
> Which version of node would work?

Try these steps below for sqlite. It works for libraries that uses compilation on windows.
https://github.com/mapbox/node-sqlite3/issues/972#issuecomment-774489345
