### ISSUE TITLE
node@8.9.3 electron@2.0.0-beat7 sqlite3@4.0.0

### ISSUE THREAD

**Issue by mingyuelou1997** [mapbox/node-sqlite3#974]
App threw an error during load
Error: **Cannot find module 'D:\TEST\electron-7\electron-quick-start-master\node_m
odules\_sqlite3@4.0.0@sqlite3\lib\binding\electron-v2.0-win32-x64\node_sqlite3.n
ode'**
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (D:\TEST\electron-7\electron-quick-start
-master\node_modules\_electron@2.0.0-beta.7@electron\dist\resources\electron.asa
r\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\TEST\electron-7\electron-quick-start-master\node_m
odules\_sqlite3@4.0.0@sqlite3\lib\sqlite3.js:4:15)
    at Object.<anonymous> (D:\TEST\electron-7\electron-quick-start-master\node_m
odules\_sqlite3@4.0.0@sqlite3\lib\sqlite3.js:190:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)

**Comment by springmeyer** [comment]
Please try the v4.0.1 release: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401 and see the docs for electron at #1006
