### ISSUE TITLE
Unable to build binaries manually from source in Windows

### ISSUE THREAD

**Issue by stevefan1999** [mapbox/node-sqlite3#989]
```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and node@10.1.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140
 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [<REDACTED>\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
```

**Comment by stevefan1999** [comment]
By forcefully using the build tools from NPM, it worked. But I don't think this is the intended behavior?

**Comment by Nostradamos** [comment]
Same problem for linux x64
`https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz`
Gets back some access denied. And it seems like the fallback to build from source fails, need to manually call it with --build-from-source.

**Comment by shepelevstas** [comment]
I guess the problem is node v10. It fails to work with sqlite3 latest 3.* version installed before upgrading to node v10, and it fails to install/build sqlite3 v4. I had to downgrade to node v8 and reinstall sqlite3 v4. I suspect upgrading to node v10 after installing/rebuilding sqlite3 v4 will not work.

**Comment by bpatrik** [comment]
same here. Fails on node v10

```
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Patrik\AppData\Roaming\npm\node_mo
dules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Work\PiGallery2\node_modules\sqlite3\lib
\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Work\PiGallery2\node_modules\sqlite3
\lib\binding\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Work\PiGallery2\node_modules\sqlite3\node_modules\node-pre-gyp\lib
\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Work\\PiGallery2\\node_modules\\sqlite3\\node_modules\\no
de-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Work\PiGallery2\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok

```

**Comment by ashishpandey001** [comment]
#994

**Comment by springmeyer** [comment]
The v4.0.1 release now supports node v10: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401
